MITLibraries/bento

app/controllers/search_controller.rb
app/models/normalize_eds.rb
app/models/normalize_google.rb
app/models/search_eds.rb
app/models/search_google.rb
app/views/search/search.html.erb
test/models/normalize_eds_test.rb
test/models/normalize_google_test.rb
test/models/search_eds_test.rb
test/models/search_google_test.rb

The search classes were getting a bit complicated because they were
concerned with both searching and normalizing. Switching to normalizer
classes allows each class to focus on a single concern.

Use normalizer classes

---

README.md
app/views/layouts/application.html.erb

This takes the stock GA code, de-minimizes it to pass the eslint check on CodeClimate, and adds a ternary check of the domain name to swap between registering activity to the test or production account.
As a first step, I think the goal is just to track pages. A further goal would be to adopt event tracking in order to record the items returned from the various tools, or to record where the user moves from the result page.
A second needed change before this launches is probably to re-consider how we check for the app being in production. I'd welcome @JPrevost thoughts here.
(I'm also happy to squash this branch before merging - so far I've been leaving the commits separate)
When merged, this closes #26.

Adds Google Analytics

---

app/assets/javascripts/static.js
app/views/layouts/application.html.erb
app/views/search/bento.html.erb

This sets up event tracking when the user clicks on `a` tags in one of four defined regions: the three bento results areas, and the "other tools" area. What regions we focus on are obviously negotiable, as are how we call the listener in the first place.
If you look at the test discovery profile within GA, you'll see what events are being received.
I'd like to hear from @JPrevost and @szendeh about the technical side of this. The decision about whether to track this, or what to record at all, is probably something that should happen in Basecamp.
When merged, this would close #43

[WIP] First stab at recording interaction events

---

app/assets/javascripts/static.js
app/assets/stylesheets/bento.css
app/views/search/_trigger_search.html.erb
app/views/search/bento.html.erb
app/views/search/search.html.erb

I'm probably doing unholy things with the ReportSummary function, but this is a starting point. I still need to make the items an internal link to the actual panels.
One question for @frrrances : the markup I'm using for the summary bar is:
```
<div class="row bento-summary">
<h3>Found</h3>
<ul class="bento-summary-list">
<li data-region="articles"><span class="count">491</span> Articles</li>
<li data-region="books"><span class="count">5</span> Local Books</li>
<li data-region="worldcat"><span class="count">7</span> Worldwide Books</li>
</ul>
</div>
```
which renders for now as 
Some of this will be addressed in the UI work, but my thought here is to make screen reader output as simple as possible, like:
`List of three items. Item one 491 Articles. Item two 5 Local Books. Item three 7 …

Implements rudimentary summary bar

---

app/views/search/_trigger_search.html.erb

Why:
* Searches with apostrophes were being redirected as having invalid
search targets. https://mitlibraries.atlassian.net/browse/DI-61
This change addresses the need by:
* Switching to `URI.encode_www_form_component` prevents javascript from
choking on the passed parameters. Previously, with `URI.encode`
javascript would lose all values in the query string after an
apostrophe, including the target parameter which was what was
causing the problems.
* We don't have any full stack integration tests for this type of work
where we do a full search in the UI, therefore no test was added which
is obviously not ideal. As the UI matures, we'll likely add some full
stack javascript-enabled tests to help ensure we don't have
regressions on this type of bug.

Updates encoding format for js triggered searches

---

app/controllers/search_controller.rb
app/models/normalize_eds_books.rb
test/models/normalize_eds_articles_test.rb
test/models/normalize_eds_books_test.rb
test/models/normalize_eds_test.rb
test/vcr_cassettes/multiple_book_authors.yml
test/vcr_cassettes/multiple_book_subjects.yml
test/vcr_cassettes/no_article_authors.yml
test/vcr_cassettes/no_book_authors.yml
test/vcr_cassettes/popcorn_books.yml

Why:
* the code that normalizes EDS article and book content did not
contain a comprehensive set of tests. The tests here should provide
better assurance that we are handling edge cases as expected.
This change addresses the need by:
* Adding lots of tests.
Tickets associated with this work:
* https://mitlibraries.atlassian.net/browse/DI-93
Merged code this is testing was tracked by:
* https://github.com/MITLibraries/bento/pull/59
* https://mitlibraries.atlassian.net/browse/DI-72
* https://mitlibraries.atlassian.net/browse/DI-73

Adds tests for normalized EDS data

---

app/models/normalize_eds.rb
app/models/normalize_eds_books.rb
app/views/search/_result.html.erb
config/environments/test.rb
test/models/normalize_eds_articles_test.rb
test/models/normalize_eds_books_test.rb

What:
* This commit provides jumpstart links into appropriate EDS
profiles to allow users to start searches for an author or
subject they click on in the bento interface.
Why:
* Users may want to run searches on specific authors or subjects
they find in our bento search in order to find more results
that are similar or related.
* https://mitlibraries.atlassian.net/browse/DI-95
* https://mitlibraries.atlassian.net/browse/DI-111
How:
* The normalized authors will now contain an array of arrays. The inner
arrays will be ['Author Name', 'Link to jumpstart search'].
* The work of creating appropriate links is done in the normalizer so
we can keep the views as clean as possible and make the logic more
easily testable with unit tests.
* Each EDS profile has an ENV that sets the base of the URL, …

Adds jumpstart search links for author and subject

---

app/models/normalize_eds_articles.rb
app/views/search/_result.html.erb
test/models/normalize_eds_articles_test.rb

What:
* This commit provides links into SFX for journals in our
articles search bento box
Why:
* Users may want to find more information about a journal rather
than linking to the specific article we have returned in the
search results
* https://mitlibraries.atlassian.net/browse/DI-112
How:
* The normalized `in` will now contain an array of Journal Title
and sfx link, like `['Journal Title', 'link to SFX for Journal']`
* The work of creating appropriate links is done in the normalizer so
we can keep the views as clean as possible and make the logic more
easily testable with unit tests

Adds link to sfx for journals

---

app.json
app/controllers/search_controller.rb
app/models/normalize_eds.rb
app/models/search_eds.rb
app/views/layouts/_institute_footer.html.erb
app/views/search/_toggle_boxes.html.erb
app/views/search/bento.html.erb
app/views/search/search.html.erb
config/environments/test.rb
test/integration/search_test.rb
test/vcr_cassettes/multiple_book_authors.yml
test/vcr_cassettes/multiple_book_subjects.yml
test/vcr_cassettes/no_article_authors.yml
test/vcr_cassettes/no_book_authors.yml
test/vcr_cassettes/no_results.yml
test/vcr_cassettes/popcorn_articles.yml
test/vcr_cassettes/popcorn_books.yml
test/vcr_cassettes/popcorn_non_articles.yml
test/vcr_cassettes/popcorn_whatnot.yml
test/vcr_cassettes/rollbar4.yml
test/vcr_cassettes/rollbar4a.yml
test/vcr_cassettes/rollbar8.yml

What:
* Adds whatnot box
* Fixes relevance
Why:
* To allow our team to better evaluate what goes in each box, it was
decided to create a temporary(?) EDS profile where we will put all the
stuff that isn't obvious where to put.
* Relevance was reported as not matching the EDS UI for the same search.
This changes from querying the API for "any" of the supplied words to
querying for "all" supplied words and seems to match the UI from my
initial testing.
See Also:
* https://mitlibraries.atlassian.net/browse/DI-121

Adds whatnot box and fixes relevance

---

app/models/result.rb
app/views/search/_result.html.erb
test/models/result_test.rb

What:
* creates a convenience method for limiting display to 3 subjects
Why:
* some records have _lots_ of subjects and it is unlikely it will be
useful to display them all
* https://mitlibraries.atlassian.net/browse/DI-127

Limit long subject lists

---

app/models/normalize_eds_articles.rb
app/models/normalize_eds_books.rb
app/models/normalize_eds_common.rb
app/models/result.rb
app/views/search/_result.html.erb
test/models/normalize_eds_articles_test.rb

What:
* This allows for articles to have distinct links for detailed record
view and get_it_url
Why:
* it was decided to always have the item title link to the record view
in the source while having the get_it link go to either the record
view or sfx depending on the type of item
* https://mitlibraries.atlassian.net/browse/DI-128
How:
* The `Result` class now supports both the required `url` as well as a
new optional `get_it_url`. The normalizers set those as appropriate
for the different types of resources.

Adds support for direct record url

---

app/models/normalize_eds_common.rb
app/models/result.rb
app/views/search/_result.html.erb

What:
* adds db source label and db source id to results from EDS sources
Why:
* While we assess what data sources should feed each box in the bento,
it will be helpful to know what data sources the specific results we
are seeing come from
* https://mitlibraries.atlassian.net/browse/DI-130

Adds db_source display

---

app.json
app/controllers/search_controller.rb
app/models/normalize_eds_articles.rb
app/models/search_eds.rb
app/views/search/search.html.erb
test/models/normalize_eds_articles_test.rb
test/models/normalize_eds_books_test.rb
test/models/normalize_eds_test.rb
test/models/search_eds_test.rb
test/vcr_cassettes/no_results.yml
test/vcr_cassettes/popcorn_articles.yml
test/vcr_cassettes/popcorn_books.yml
test/vcr_cassettes/popcorn_non_articles.yml
test/vcr_cassettes/rollbar4.yml
test/vcr_cassettes/rollbar4a.yml
test/vcr_cassettes/rollbar8.yml

What:
* Moves from multiple EDS Admin configured profiles to a faceted
approach that uses the source facet to segregate content into
appropriate boxes
Why:
* EDS profiles would never allow us to create the boxes we were asked
to create because we were basing the boxes on format of the material
and profiles can't be created effective that way.
* https://mitlibraries.atlassian.net/browse/DI-136
How:
* Facets for the (currently 3) boxes are configured via the ENV settings.
EDS_ARTICLE_FACETS, EDS_BOOK_FACETS, EDS_WHATNOT_FACETS
Note:
* The link to more like this is temporarily disabled as we look into how to
deep link into pre-faceted result sets in EDS UI. That issue is tracked
via https://mitlibraries.atlassian.net/browse/DI-143

Refactor from EDS profiles to EDS Facets

---

app/assets/stylesheets/libraries-global.css
app/views/layouts/application.html.erb

This PR adds a static beta banner to the bento app - that can also be used to wire in app-level/global-level notifications at some point.

add app global notice/alert

---

app.json
app/views/layouts/_flash.html.erb
app/views/layouts/_global_alert.html.erb
app/views/layouts/application.html.erb
test/integration/alerts_test.rb

What:
* Adds an ENV based global alert system
Why:
* Initially, this will be used to signify test and beta instances of our
application. Eventually, this may be used to signify other globally
relevant application level information (such as known planned API
outages, etc)
* See: https://mitlibraries.atlassian.net/browse/DI-141
How:
* ENV['GLOBAL_ALERT'] can be set like 'This is a beta site. You may be
interested in our
<a href="/some_url">production discovery environment.</a>'
* By using ENV['GLOBAL_ALERT'] we can always set our test ENVs to link
back to Prod versions, etc

Adds global alert system

---

app/assets/stylesheets/bento.scss
app/assets/stylesheets/libraries-global.css
app/views/layouts/_about-bento.html.erb
app/views/layouts/application.html.erb

This PR adds an "About bento" informational block to the bottom of the bento pages. 
NOTE: Copy is still TBD but shippable.

add about bento block

---

app/controllers/search_controller.rb
app/models/normalize_eds.rb
app/models/normalize_google.rb
app/views/search/_view_all_link.html.erb
config/environments/test.rb
test/models/normalize_eds_articles_test.rb
test/models/normalize_eds_books_test.rb
test/models/normalize_eds_test.rb
test/models/normalize_google_test.rb
test/models/search_eds_test.rb
test/vcr_cassettes/popcorn_articles.yml
test/vcr_cassettes/popcorn_books_paginated.yml
test/vcr_cassettes/popcorn_non_articles.yml

What:
* Allows a toggle between viewing local paginated results and results
in EDS UI
* The default is EDS UI
* This is a global setting
* To enable local paginated results, set Environment Variable
`LOCAL_RESULTS=true`
Why:
* It is still not clear whether we want to send people to EDS UI or use a
local solution for this feature
* This feature toggle will allow us to test both options to make an
informed decision on what is best
* See https://mitlibraries.atlassian.net/browse/DI-178

Di178 view more toggle

---

app/models/search_eds.rb
app/views/search/_trigger_search.html.erb
config/environments/development.rb
config/initializers/rollbar.rb

What:
* This presents an error message to users when things go awry during the
XHR requests
* This does not try to get fancy and report errors from the client side,
but instead assumes the errors would have been logged during the rails
server side processing (which is probably true)
* It does log to the end user's JavaScript console the xhr response when
this is triggered so in theory we could work with tech savvy users to
get a copy of the request if necessary (probably not)
* This also adds a timeout of 6 seconds to the EDS API calls and logs
all URLs to EDS for debug purposes
* Disables rollbar and enables more logging in dev environment
Why:
* The previous fail state was an infinitely spinning loader image which
was obviously not too helpful
Note:
* see also …

Di59 result error handling

---

app/models/normalize_eds_articles.rb
app/models/normalize_eds_books.rb
app/models/result.rb
app/views/search/_result.html.erb

What:
* adds Result.get_it_label
Why:
* a single label for all get_it_urls was not clear to users
See also:
* https://mitlibraries.atlassian.net/browse/DI-180

Adds get_it_label so get_it_url can be customized

---

app/assets/stylesheets/bento.scss
app/views/layouts/_global_alert.html.erb
app/views/layouts/_site_footer.html.erb

I realized that there were 2 small fixes that ATIC recommended outside issues which are in this PR: make the alert a little more findable since it's outside the main area, and remove the redundant aria label on the nav since the header is doing the same thing.

small a11y fixes

---

app.json
app/models/normalize_eds_books.rb

What:
* To ensure we send users consistently to the expected detail page
in EDS, we need to pass some additional information to the link
we extract from the EDS record.
Why:
* Not passing in the profile information sent users sometimes to an
unexpected profile.
How:
* ENV `EDS_PLINK_APPEND` will now append parameters to the extracted URL
to allow for targeting specific profiles.

Pass profile info with detail links

---

app/models/normalize_eds_books.rb
app/models/normalize_eds_common.rb

When we added profile information to get_it_urls for books, we didn’t
update the title link which for books also links to the same profile
page.
This change ensures they use the same code to set both links.

Books record link fix

---

Gemfile
Gemfile.lock
app.json
app/controllers/feedback_controller.rb
app/views/feedback/index.html.erb
test/integration/feedback_test.rb
test/test_helper.rb

What
- adds recaptcha to feedback form
- uses test keys in pr build
Why
- to prevent spam

Add Recaptcha to Feedback Form

---

app/controllers/search_controller.rb
config/environments/test.rb

* The new default is 20 per page for paginated results
* `ENV[‘PER_PAGE’]` is available to change that
* passing in a `per_page` URL parameter remains an option as well

Defaults to 20 per page for paginated results

---

app/assets/stylesheets/feedback.scss
app/controllers/feedback_controller.rb
app/mailers/feedback_mailer.rb
app/views/feedback/index.html.erb
app/views/feedback_mailer/feedback_email.html.erb
test/controllers/feedback_controller_test.rb
test/fixtures/feedback_mailer/feedback_email
test/mailers/feedback_mailer_test.rb

- removes feedback placeholders
- adds optional name to feedback form
see https://mitlibraries.atlassian.net/browse/DI-221

Feedback Form Updates

---

app/views/feedback_mailer/feedback_email.html.erb
test/controllers/feedback_controller_test.rb
test/fixtures/feedback_mailer/feedback_email

What:
* removes a line from the feedback email
Why:
* to allow easier quick scanning when previewing email
See: https://mitlibraries.atlassian.net/browse/DI-244

Removes unnecessary info from feedback email

---

app/models/result.rb
test/models/result_test.rb

What:
* This only uses marc856 links we know to be useful
Why:
* We store a lot of not-so-useful for this purpose links in our
MARC 856

Only use relevant marc856 links

---

app/models/normalize_eds_common.rb

EDS upstream fix to our sso access seems to have forced sso into our
EDS API result links. This is a hacky way to address that while we
consider better options

Remove authtype=sso

---

app/controllers/catch_all_controller.rb
app/views/catch_all/catch_all.html.erb
config/routes.rb
test/integration/catch_all_test.rb

This just puts the 404s in our site template for now.
5xx is less simple due to the nature of 5xx meaning it's best to use static pages so we need to do more work.

Wrap 404s in site template

---

app/models/result.rb
app/views/search/_result.html.erb
test/models/result_test.rb

What:
* Detects and handles aleph course reserve records
Why:
* Aleph Realtime Availability was failing due to not detecting the
pattern used for course reserve records in EDS API results
* https://mitlibraries.atlassian.net/browse/DI-257

Detect and handle Aleph Course Reserve records

---

app/views/layouts/_about-bento.html.erb

This PR adds a link to the information about page on the main libraries site.

add link to about page

---

app/models/normalize_eds_common.rb

This returns from the method if the name we are trying to select
doesn’t exist in the returned data. Ooops.

bugfix: return from extract_by_name

---

app/views/search/_result.html.erb

If the realtime status is offline, we need to note that with the location info to prevent people from running to the stacks in excitement and being disappointed that it's checked out.

add not realtime words if offline

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/bento.scss
app/assets/stylesheets/results.scss
app/models/normalize_eds_common.rb
app/models/result.rb
app/views/search/_debug.html.erb
app/views/search/_result.html.erb
test/models/normalize_eds_articles_test.rb
test/models/result_test.rb

What:
* Removes record links (eds ui detail view) from GetIt link
* Removes constructed openurls from GetIt link
* Extracts both fulltext and record links from EDS
* Adds record link as a button (only using EDS UI link for now)
* Renames GetIt Link to reflect it should lead towards online
full text links
* Splits record debug to a partial to make it easier to scan the main
record view
Why:
* The single button doing so much was potentially leading to confusion
for end users

Removes Record Links from GetIt Link

---

app/controllers/search_controller.rb

- this fixes a bug where the logic to determine whether to show a view more link
broke if `RESULTS_PER_BOX` was set

Numbers are not strings

---

Gemfile
Gemfile.lock
app/views/search/_result.html.erb
config/application.rb
config/environments/development.rb
config/environments/test.rb
config/features.rb
config/routes.rb

What:
* uses flipflip gem to allow feature toggles
* changes debug mode to check via flipflop
Why:
* as we want to roll out bigger changes, it will be easier to allow them
to merge into master before we are ready to make them public by
leaving them switched off by default so we can test them in staging
and/or in production with select users
How:
* For now, this just uses session based features but the gem supports
postgres or redis backed feature enabling which may be desirable in
some situations
* in development, you can access `/flipflop` to toggle your features
* in production, this is currently disabled so we are using the same
debug enabler to set the session key the same way we did before. If we
end up with lots of features (unlikely) that are all toggleable we may
want to implement …

Enable flipflip feature flags

---

.travis.yml
app.json
app/controllers/application_controller.rb
config/application.rb
config/environments/development.rb
config/environments/test.rb
test/features/flipflop_dashboard_test.rb
test/integration/flipflop_test.rb

What:
* adds shared secret key access to flipflop controller in all
environments (dev / test were previously always accessible)
* travis defaults to running `rake`, new way is `bin/rails test`
Why:
* the ability to easily toggle features for staff in PR and staging
builds where they can confirm their current settings requires some
form of dashboard and flipflop comes with one so why not use it
How:
* setting `ENV['FLIPFLOP_KEY']` and passing that value like
`/flipflop?flipflop_key=thatthingyouset` will provide access to the
dashboard where you can see all possible toggles and easily toggle
features for your session
* if you don't set `ENV['FLIPFLOP_KEY']` all access is denied to the
dashboard but you can still toggle features via the
`/toggle?feature=yourfeature` route

Adds access control to flipflop controller

---

config/environments/production.rb

This accomplishes the same thing but uses the new non-deprecated syntax
to achieve it
closes #155

Replace deprecated syntax

---

app/models/normalize_eds_common.rb
config/environments/development.rb
config/environments/test.rb
test/models/normalize_eds_test.rb
test/vcr_cassettes/turn_of_the_screw.yml

Metadata with no relationships when reading year
* metadata that came back from EDS that did not contain
`IsPartOfRelationships` would fail when trying to extract the year
from that section
* this handles that case by confirming the expected sections exist
before trying to access them
See https://mitlibraries.atlassian.net/browse/DI-288
This also adds an option to log like production during local development.

288 nomethod error

---

app/views/search/_other_resources.html.erb

Removes the link to Yewno in the other resources since we aren't currently supporting it.

Remove yewno link

---

app/models/search_eds.rb
test/models/search_eds_test.rb
test/vcr_cassettes/custom_timeout.yml

What:
* it is now possible to control the timeout via an Environment
setting for EDS API calls
Why:
* there are times with EDS doesn't seem to be responding in an
acceptable amount of time
* while we feel EDS should fix this, it is likely there will be
times when we want to bump our timeout a bit higher just to allow
users to search even if it takes way too long

Allows ENV configurable http_timeout in EDS Search

---

app/models/result.rb
test/models/result_test.rb

What:
* consider proxied links relevant
* if custom_links have both sfx and proxied links, prefer proxied
Why:
* the proxied links have been determined to be more reliable
How:
* the sort currently only prioritizes proxied links. If we need to sort
in a more complex way, say by the order in `relevant_links`, more work
will need to be done to ensure the sort always works as intended. This
is entirely fine for our current use case.
See https://mitlibraries.atlassian.net/browse/DI-296

Uses proxied links and prefers them over sfx links

---

app/views/search/bento.html.erb
app/views/search/search_boxed.html.erb

What:
* adds realtime availability and ga link tracking when using the local
view more feature
Why:
* it was a bug it wasn't working
How:
* added parent div to results like we have in bento view so we can
target results with javascript functions
See: https://mitlibraries.atlassian.net/browse/DI-243

Realtime avail and Link Tracking for Local browse

---

app/models/aleph_item.rb

* we were looking for `New Books Display` but aleph uses
`New Books Displ`

Changes new books display to use correct string

---

app/models/normalize_eds_books.rb
app/models/normalize_eds_common.rb
app/views/search/_result.html.erb
test/models/normalize_eds_articles_test.rb
test/models/normalize_eds_books_test.rb

* local_browse feature now uses in_app links instead of external links
to EDS UI for authors and subjects
* external links are still used when local_browse is not enabled
NOTE: I'm not sure this is actually working as intended as I don't seem to get identical results browsing locally and via the EDS UI options.
HINT: https://mit-bento-staging-pr-182.herokuapp.com/toggle?feature=local_browse

Adds in-app subject and author links

---

app/models/result.rb
app/views/search/_result.html.erb
test/models/result_test.rb

What:
* `Result#truncated_title` truncates on full words less than the
configured value of `ENV['MAX_TITLE_LENGTH']` or 150 if unset
* `...` is appended to better identify when this is taking place in
the UI
Why:
* some titles are way too long
See: https://mitlibraries.atlassian.net/browse/DI-306

Truncate title display

---

app/assets/stylesheets/_bento.scss
app/views/search/_view_all_link.html.erb

* we were not adding the view more link when we had fewer results in
the box than the per_box max which prevented the data elements from
being present for the javascript to use to populate the summary bar
* this adds the view more link back to the dom and adds an `hidden`
css class
* one day, Frances promises she will make that class something useful
https://mitlibraries.atlassian.net/browse/DI-302

Keep view more link in dom when not displaying

---

app/views/search/_result.html.erb

What:
* flag title values as html_safe so they won't be escaped and thus
display properly.
Why:
* nobody wants to see `&amp;`
See: https://mitlibraries.atlassian.net/browse/DI-329

Flag title values as html_safe because they are

---

app/views/layouts/_about-bento.html.erb
app/views/layouts/_breadcrumbs.html
app/views/layouts/_head.html.erb
app/views/layouts/_site_header.html.erb

This PR changes references to "Discovery" to "Quick search" or just generic "search" since we don't want to name this app (yet).

Change name to generic or quick search

---

app/models/search_eds.rb

EDS seems to treat colons as a special character. Encoding them
explicitly seems to work okay.
https://mitlibraries.atlassian.net/browse/DI-360

Handle multiple colons in searchterm

---

.travis.yml
test/test_helper.rb

What:
* allows optional, via ENV['SPEC_REPORTER'], more detailed test
output
Why:
* in CI, and sometimes locally, it's nice to see the SpecReporter
test output

Allow SpecReporter format and enable on CI

---

app/models/result.rb
app/views/search/_result.html.erb
config/features.rb
test/models/result_test.rb

What:
* detects sfx links from EDS that are in our not-subscribed bucket and
prevents them from being used in the View Online button
* adds non-subscribed sfx links to a new button with a feature flag
Why:
* having the view online button lead to an sfx page that only allowed
ILL was not desired
* non-subscribed sfx however remain useful, so feature flagging the new
button for testing allows us to assess our next steps
https://mitlibraries.atlassian.net/browse/DI-371

Split EDS supplied sfx links by subscribed bucket

---

app/views/layouts/_about-bento.html.erb

The about link should now point to the non-beta about page link.

update about link to point to prod version

---

.github/PULL_REQUEST_TEMPLATE.md

What:
* adds a pull request template
Why:
* standardizing the information in our pull requests will make
reviewing code easier
Documenation: https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

Adds preliminary github pull request template

---

Procfile
db/migrate/20150101010101_devise_create_users.rb

**READY**
To date, the bento app has not used a database. This gets us set to use one by running the
database migrations during the release phase.
https://devcenter.heroku.com/articles/release-phase
This is entirely a Heroku side thing. It won't be noticeable until we do a PR _after_ this is merged.
None
NO (ha!)
NO (pg was already provisioned, we just weren't using it)

Migrates database during heroku release phase

---

app/controllers/hint_controller.rb
app/models/application_record.rb
app/models/hint.rb
app/views/hint/hint.html.erb
app/views/search/_trigger_hint.html.erb
app/views/search/bento.html.erb
config/features.rb
config/routes.rb
db/migrate/20170623172641_create_hints.rb
db/schema.rb
test/controllers/hint_controller_test.rb
test/fixtures/hints.yml
test/models/hint_test.rb

**READY**
This allows for phrase matching of search queries to suggested
'best bets' to display in a placard system.
Users are having difficulty locating some items. As the search engine is vended, we cannot adjust the upstream settings directly (we are working with them to address immediate concerns). This system will allow us to intervene in such cases that the search engine predictably does not return expected results.
This is preliminary work currently behind a feature flag. Additional work will be done
before we make this a public facing feature.
- migrate your db to get the latest schema (see below)
- create a Hint using a rails console: `heroku local:run rails console`
- in the rails console:
`Hint.create(title: 'yo title', url: 'http://example.com/get/stuff', fingerprint: …

Initial system to store local search hints

---

app/models/result.rb
test/models/result_test.rb

**READY**
a change to how we handle "get URLs" necessitates we include the
libraries.mit.edu domain in our `relevant_links`
In order to not use irrelevant links to t.o.c or publisher sites that we include in our MARC records, we only count links to "relevant" domains as links for our `View Online` links.
Once the data is loaded from our test barton catalog into the test EDS profile, searching for records with get urls should provide that URL directly as the "View Online" url rather than as a passed parameter in a SFX url.
- https://mitlibraries.atlassian.net/browse/DI-436
NO
NO

Include libraries.mit.edu domain in relevant_links

---

app/controllers/search_controller.rb

**READY**
this explicitly sets the cache of search results to expire
* memcachier is supposed to purge based on LRU, but we have seen in
production that didn't happen with our current configuration
* the intent here is to set cached items to explicitly expire so
hopefully they will be purged appropriately as expected
* we'll need to monitor the results of this change to ensure it is
working as intended (the cache size on staging is much smaller so
we can use that to confirm expected results before production cache
size gets large enough to be a concern)
Sadly, you can't really :/
- https://mitlibraries.atlassian.net/browse/DI-383 (sort of)
NO
NO

Explicitly set cache expiration

---

.gitignore
README.md
app/models/aleph_hint.rb
app/models/hint.rb
db/migrate/20170727185125_add_source_to_hints.rb
db/schema.rb
lib/tasks/reloadhints.rake
test/fixtures/hints.yml
test/models/aleph_hint_test.rb
test/models/hint_test.rb

**READY**
* adds `Hint.source` to allow for reloading of hints more easily
* adds `Hint.upsert` to allow loaders to defer duplicate logic to the   `Hint` model
* updates `AlephHint` loader to supply a `Hint.source`
* adds ActiveRecord validations to Hint
* add reload method to AlephHint to allow for one step drop / reload
* rollback on failed AlephHint loads
* adds task to easily run the AlephHint loader
First delete any `Hints` in your local database and run the database migrations.
With a valid `ALEPH_HINT_SOURCE` set in your `.env` (ask if you need a source or grab it from Heroku), run `heroku local:run bin/rails reloadhints:aleph`
You should now have a set of non-duplicate Hints all from the aleph source.
You can manually add more records to the aleph source and re-run that task to …

451 hint source

---

app/models/aleph_hint.rb
test/models/aleph_hint_test.rb

**READY**
* creates fingerprints from additional title-like fields
There are lots of title-like fields in MARC. "helpful" background context ;)
- Reload the Aleph hints:
```
heroku local:run bin/rails reloadhints:aleph
```
- Search for `IEEE xplore`
- 🍻 
... OR, just search in the PR build for `IEEE xplore` and compare the staging for the same.
- https://mitlibraries.atlassian.net/browse/DI-456
NO
NO

Creates fingerprint from additional MARC fields

---

app/helpers/feature_helper.rb
app/helpers/hint_helper.rb
app/views/hint/hint.html.erb
test/helpers/hint_helper_test.rb
test/models/hint_test.rb

**READY**
This updates our Hint placards as follows:
- uses `Hint.title` as the link text for the main link
- displays and links the `Hint.url` on a separate line only if it is a "get" URL
- makes a distinction in the UI between a 'custom' `Hint.source` and any other `Hint.source`
Misc
- removes some skipped Hint tests for a feature we’ll likely never implement
- removes an unused Helper file
After enabling the feature on the PR build via https://mit-bento-staging-pr-235.herokuapp.com/toggle?feature=hints
Searching for:
- `pubmed` will show the logic for a custom link and get url logic
- `popcorn` will show the non-custom link, non-get url logic
- `42` will show the non-custom link with get-url logic
- https://mitlibraries.atlassian.net/browse/DI-465
NO
NO

Update Hint Placard UI

---

app/models/custom_hint.rb
test/models/custom_hint_test.rb
test/vcr_cassettes/custom_hint_blank_fingerprints.yml

Users may have added new search terms to the custom spreadsheet -
they probably don't know how to calculate fingerprints, so we should do
that when fingerprints are absent.
**READY**
Adds fingerprints as needed when loading CustomHints.
While I generated the original custom hint spreadsheet via a data dump which included calculated fingerprints, in testing we decided there are additional custom terms we should hint on. Humans adding rows to the spreadsheet are unlikely to know how to calculate hints, so we should make sure to fill them in.
If you've got this branch on localhost in your vagrant,
`heroku local:run rails reloadhints:custom[https://www.dropbox.com/s/vm2xetxclk543zv/custom%20hint%20for%20test%20suite.csv?dl=1]`
Or the equivalent command on the PR build.
In the rails console, …

Calculate fingerprints as needed when loading CustomHints

---

README.md
app/models/hint.rb
test/fixtures/hints.yml
test/helpers/hint_helper_test.rb
test/models/aleph_hint_test.rb
test/models/custom_hint_test.rb
test/models/hint_test.rb

**READY**
Allows us to set an environment variable listing the Hint sources we display to the user, in order of priority.
We may have hints with the same fingerprint from multiple sources (e.g. one automatically generated from aleph and one manually entered by staff on the spreadsheet); we need a tiebreaker mechanism.
* In your console, create Hints that both have a fingerprint of `pubmed`, one whose source is `custom` and one whose source is `aleph`
* `Hint.match('pubmed')` and observe that you get the custom-sourced one
* Set `ENV['HINT_SOURCES'] = 'custom,aleph'`; note that `Hint.match('pubmed')` returns the custom-sourced hint
* Set `ENV['HINT_SOURCES'] = 'aleph,custom'`; note that `Hint.match('pubmed')` returns the aleph-sourced hint
* Set `ENV['HINT_SOURCES'] = 'fake'`; note that …

451 prioritize by source

---

config/features.rb

**READY**
We are leaving the feature flag in place, but defaulting to enabled to
allow us to easily turn it back off if this does not go over well. We
will remove the feature flag once this is stable in production.
I'll load the PR build with CustomHints. You should be able to search in the PR build for something that should return as a Hint and see it without manually enabling the feature.
- https://mitlibraries.atlassian.net/browse/DI-484
NO
NO

Sets Hints feature to enabled by default

---

app/assets/stylesheets/_hint.scss

**READY**
Fixes a text overlap in hints UI when on a small screen.
- https://mitlibraries.atlassian.net/browse/DI-487
Before:
After:

adjust hint on mobile to prevent text overlap

---

README.md
app/views/layouts/_head.html.erb

**READY**
This enables the [Linker plugin](https://developers.google.com/analytics/devguides/collection/analyticsjs/linker) as part of our Google Analytics infrastructure. This is part of our attempt to work toward seamless reporting on the functioning of our discovery environment.
Traditionally, separate web applications each have a separate GA profile. However, when multiple web applications are functionally one environment, this approach breaks down. The discovery environment is one such case, where users start in one location (typically the public homepage) and then proceed through multiple tools (Bento, EDS, SFX, etc) on their way to complete their task.
Through the Linker plugin and cross-domain referral exclusion lists, Google Analytics makes it possible to get information about …

491 Enables Google Analytics linker plugin

---

app/controllers/search_controller.rb
app/models/search_eds.rb
test/integration/search_test.rb
test/models/search_eds_test.rb
test/vcr_cassettes/bad_eds_session.yml

**READY**
* EDS sometimes does not accept session tokens they have created
* detect and log when that happens
* attempt to create a new session token, but only once, when detected
to hopefully provide end users with a reliable experience even when
our upstream source is being flakey
* throw an exception if the bad token is detected on two consecutive attempts during a single  
request
Sadly, there is no great way without changing the code. However, this is how to change the code to see what should happen.
In `search_eds.rb` model, change line 70 from `return unless eds_session_invalid?(result)` to `return if @attempts == 1`. When running a local search, your logs should now show the detection of a bad token, a retry, and then your search should succeed (unless you somehow manage to do …

Handle bad EDS Session Tokens

---

app/views/record/record.html.erb

**READY**
This adds a class and data attribute to the full record view so that interactions with that interface are recorded separately in Google Analytics.
Prior to this change, interactions with the app are broken up into several categories:
* Books and media
* Articles and journals
* Library website and guides
* Other resources
* Link (this is the catchall category, if another value is not found)
Without this PR, interactions with the record page will be recorded in the Link category, which is potentially confusing down the road.
Load a full record, inspect the markup to see the new class and data attributes.
Watch Google Analytics to see the new event classification come in when you click on a link on the record panel.
- https://mitlibraries.atlassian.net/browse/DI-501
NO
NO

Add markup to separate full record panel in analytics

---

app/models/search_eds.rb

**READY**
We were seeing session failures and then I pushed the retry code and never saw any logs stating we were recovering as expected. This updates log levels to see if the problem went away or if we were actually recovering but not logging.
NO
NO

Update log levels

---

app/helpers/search_helper.rb
app/views/search/_result.html.erb
config/features.rb

**READY**
Allows bento results to display links to either the EDS UI (default) or local full records.
This is accessed via the feature toggle `local_full_record`
In the PR build, you can enable the toggle via:
https://mit-bento-staging-pr-250.herokuapp.com/toggle?feature=local_full_record
- https://mitlibraries.atlassian.net/browse/DI-498
NO
NO

Adds feature flag to local full records

---

app/assets/javascripts/search.js
app/controllers/aleph_controller.rb
app/helpers/aleph_helper.rb
app/helpers/record_helper.rb
app/views/aleph/full_item_status.html.erb
app/views/record/_availability.html.erb
app/views/record/_basic_info.html.erb
app/views/record/_extended_info.html.erb
app/views/record/_links.html.erb
app/views/record/_sidebar.html.erb
app/views/record/record.html.erb
config/routes.rb
test/controllers/record_controller_test.rb
test/helpers/aleph_helper_test.rb
test/integration/aleph_test.rb
test/integration/record_test.rb
test/models/hint_test.rb
test/vcr_cassettes/record_status_archives.yml
test/vcr_cassettes/record_status_barker.yml
test/vcr_cassettes/record_status_dewey.yml
test/vcr_cassettes/record_status_hayden.yml
test/vcr_cassettes/record_status_music.yml
test/vcr_cassettes/record_status_reserve.yml
test/vcr_cassettes/record_status_rotch.yml

**READY**
- Moves full record sections to partials
- Adds call to aleph API for local non-serial records and does initial logic for the various buttons we want to display. The buttons are not linking to where they need to go yet (https://mitlibraries.atlassian.net/browse/DI-513).
- Serial records will be handled via a separate process to display holding records (https://mitlibraries.atlassian.net/browse/DI-512).
- full text links will be handled in a separate ticket (https://mitlibraries.atlassian.net/browse/DI-514)
In the PR build, enable Full Record displays ( https://mit-bento-staging-pr-251.herokuapp.com/toggle?feature=local_full_record ) then search for things we own locally and see the resulting realtime availability work for book-like things but not serial-like things. Some Items …

Initial full record realtime availability

---

app/assets/stylesheets/libraries-global.scss

**READY**
Updates global css to include a fix the alignment of the MIT logo in the footer and add css that supports expand-collapse.
MIT logo in the footer should now be next to the text instead of above it.
- https://mitlibraries.atlassian.net/browse/DI-511

update lib global css

---

Gemfile
Gemfile.lock
app/controllers/hint_controller.rb
app/views/hint/hint.html.erb
config/features.rb
test/controllers/hint_controller_test.rb
test/vcr_cassettes/ga_hint_tracking.yml

**READY**
This improves our analytics capabilities around hints. Specifically, it:
- records interactions with hints in their own action, instead of alongside other branding elements.
- uses the staccato gem to record the _display_ of hints, in addition to just when users click on them.
- Inspect the markup around a displayed hint to see a data attribute for the container.
- Watch the real time events panel in Google Analytics to see server-side analytics when they are displayed.
- Watch the real time events panel in Google Analytics to see how interactions with hints are now re-classified in the `Bento / Hints` category / action, rather than `Bento / Link`
- https://mitlibraries.atlassian.net/browse/DI-474
NO
YES

Records existance of hint in google analytics via staccato gem

---

app/assets/stylesheets/_aleph.scss
app/helpers/aleph_helper.rb
app/views/aleph/full_item_status.html.erb
test/integration/aleph_test.rb

This PR adds semantic/layout html and styles to format the availability block on the full record page.
View a record on the sandbox, like `record/cat00916a/mit.001134881`
- https://mitlibraries.atlassian.net/browse/DI-504
Should match mockups: https://mitlibraries.atlassian.net/wiki/spaces/DI/pages/32833537/Full+record

full record availability layout and styles

---

app/controllers/concerns/rainbows.rb
app/controllers/record_controller.rb
app/helpers/record_helper.rb
app/views/record/_extended_info.html.erb
app/views/record/_more_information.html.erb
app/views/record/record.html.erb
config/features.rb
config/rainbows.yml
test/concerns/rainbow_concern_test.rb
test/controllers/record_controller_test.rb
test/helpers/record_helper_test.rb
test/integration/record_test.rb
test/vcr_cassettes/record_not_fulltext.yml
test/vcr_cassettes/record_rainbows.yml

**READY**
Adds the more-information section to the full record page. See wireframes: https://mitlibraries.atlassian.net/wiki/spaces/DI/pages/32833537/Full+record
Does *not* make it pretty - that will be for @frrrances later.
Super secretly also adds the feature we discussed with CB at Randi's party. Shhh, don't tell her yet. 
To see the effect of the 479 work: PR build, toggle feature `local_full_record` on, look at item record pages. Behold! Information!
To see the super secret bonus feature: PR build, toggle feature `pride` on, find something with LGBT subject headers. 🌈 !
- https://mitlibraries.atlassian.net/browse/DI-479
NO
NO

479 extended info

---

app/helpers/record_helper.rb
app/views/aleph/_list_local_locations.html.erb
app/views/aleph/full_item_status.html.erb
app/views/record/_availability.html.erb
test/integration/record_test.rb

**READY**
Removes condition that prevented local serials records from getting realtime availability displays.
Adds support for collapsible availability lists.
Both features this adds can be seen here:
https://mit-bento-staging-pr-260.herokuapp.com/record/cat00916a/mit.000953977
And comparing to:
https://mit-bento-staging.herokuapp.com/record/cat00916a/mit.000953977
- https://mitlibraries.atlassian.net/browse/DI-512 (completed with this work)
- https://mitlibraries.atlassian.net/browse/DI-503 (completed with this work)
NO
NO

Local serial availability

---

app/helpers/record_helper.rb
app/views/record/_availability.html.erb
app/views/record/_extended_info.html.erb

**READY**
This adds a `safe_output(input)` helper which handles the sanitization of html
in API supplied metadata while also handling poorly formed HTML (which
the internal Rails methods seem to have some issues with).
Before change see notes section here:
https://mit-bento-staging.herokuapp.com/record/cat00916a/mit.000953977
After change see note section here:
https://mit-bento-staging-pr-264.herokuapp.com/record/cat00916a/mit.000953977
- https://mitlibraries.atlassian.net/browse/DI-548
NO
NO

Adds safe_output helper

---

README.md
app.json
app/controllers/record_controller.rb
app/helpers/login_helper.rb
app/helpers/record_helper.rb
app/helpers/search_helper.rb
app/views/record/_availability.html.erb
app/views/record/record.html.erb
test/vcr_cassettes/record_article.yml
test/vcr_cassettes/record_bananas.yml
test/vcr_cassettes/record_book.yml
test/vcr_cassettes/record_course_reserve.yml
test/vcr_cassettes/record_journal.yml
test/vcr_cassettes/record_no_such_database.yml
test/vcr_cassettes/record_not_fulltext.yml
test/vcr_cassettes/record_rainbows.yml
test/vcr_cassettes/record_sfx_fulltext.yml

**READY**
Activates guest mode for full record views.
Provides links to proxy site in production and override guest mode in development/test.
From a non-MIT IP access restricted records and records with expiring direct links.
https://mit-bento-staging-pr-262.herokuapp.com/record/mdc/25750248
From a non-MIT IP, instead of a direct PDFLINK, you'll see a link to sign in. Once signed in, you'll get the direct PDFLINK.
Any other redacted information should automatically be suppressed by the guest mode included in this PR (but I don't have examples of other content that is only accessible to signed in users).
- https://mitlibraries.atlassian.net/browse/DI-497
Guest mode
non-Guest mode
NO
NO

497 login prompt

---

app/controllers/errors_controller.rb
app/controllers/record_controller.rb
config/application.rb
config/routes.rb
test/controllers/record_controller_test.rb

**READY**
Allows for more characters in full record URLs (e.g. we think we may encounter hyphens).
If you know of an example record which has a hyphen in its accession number, go to its URL in the PR build.
- https://mitlibraries.atlassian.net/browse/DI-532
NO
NO

Expand options for characters in URLs

---

app/assets/stylesheets/_aleph.scss
app/assets/stylesheets/_full-record.scss
app/assets/stylesheets/application.scss
app/views/record/_availability.html.erb
app/views/record/record.html.erb

**READY**
Adjust the prompt to authenticate when viewing a full record from not-an-MIT-IP. 
Go off campus and try to view a full record. Or fire up the VM and add ?guest=true to a full record URL.
- https://mitlibraries.atlassian.net/browse/DI-520
NO
NO

Add style for full record auth states

---

app/views/record/record.html.erb
test/integration/record_test.rb
test/vcr_cassettes/record_access_restriction.yml
test/vcr_cassettes/record_no_access_restriction.yml
test/vcr_cassettes/record_pdflink_unrestricted_record.yml

**READY**
Adds a condition to prevent login link for records that have no restricted / redacted information.
Access Level values:
1 – Should have a placeholder
2 – Should log in to see details
3+ Should be ok in Guest
Unrestricted record shows no login button (even to guests):
https://mit-bento-staging-pr-269.herokuapp.com/record/cat00916a/mit.001739356
Restricted record shows login button to guests:
https://mit-bento-staging-pr-269.herokuapp.com/record/lah/20123379364
Unrestricted record with a pdflink shows (a slightly different) login button to guests but not the regular login button:
https://mit-bento-staging-pr-269.herokuapp.com/record/mdc/25750248
- https://mitlibraries.atlassian.net/browse/DI-559
NO
NO

Don't show login if record is unrestricted

---

app/helpers/record_helper.rb
app/views/record/_availability.html.erb
test/helpers/record_helper_test.rb

**READY**
Only considers something full text if it is going through SFX, our
catalog (which is probably going to end up in SFX), or Ebscohost.
This is very similar to, but not identical to, the code in the Result
model we use for the initial Bento results pages.
We often find links in our catalog records to non-fulltext resources, such as Publisher pages or Table of Contents pages.
New behavior (no View online button since we filtered out most domains): 
https://mit-bento-staging-pr-268.herokuapp.com/record/cat00916a/mit.001738931
Old behavior (link to ToC from View online button):
https://mit-bento-staging.herokuapp.com/record/cat00916a/mit.001738931
- https://mitlibraries.atlassian.net/browse/DI-539
NO
NO

Restrict what we consider full text links

---

app/controllers/record_controller.rb
app/helpers/record_helper.rb
app/views/record/_availability.html.erb
config/routes.rb
test/controllers/record_controller_test.rb
test/integration/record_test.rb
test/vcr_cassettes/record_direct.yml
test/vcr_cassettes/record_direct_invalid.yml
test/vcr_cassettes/record_view_online.yml

**READY/**
EDS API sometimes returns expiring URLs. To allow users to have a
pleasant experience, we suppress display of those URLs until the users
clicks the "View Online" button at which point we ask for a _new_ copy
of the expiring URL and then redirect the user to that non-expired
version.
Also includes support to ensure guests are not taken to expiring URLs
as they are not authenticated on the target system.
On staging, go to https://mit-bento-staging.herokuapp.com/record/mdc/25750248
Note the View Online is an actual direct link (it will eventually expire and you'd be sad)
On the pr build, the same record https://mit-bento-staging-pr-272.herokuapp.com/record/mdc/25750248
Note the View Online link is a local route that will fetch a new copy of the EDS data and then redirect you to …

Adds expiring URL support

---

app/models/search_eds.rb
test/models/search_eds_test.rb
test/vcr_cassettes/eds_general_error.yml

**READY**
This detects and throws a specific exception when we detect EDS has returned an error.
Before this code, we through a generic exception that was not clear what was happening.
End user experience will remain the same as we handle the exception state in the UI in either case the same way.
- https://mitlibraries.atlassian.net/browse/DI-567
NO
NO

Handle Generic EDS errors

---

app/views/search/bento.html.erb
config/features.rb

**READY**
Removes hint toggle remnants since we have had them on by default for quite some time now.
- https://mitlibraries.atlassian.net/browse/DI-535
NO
NO

Remove hints feature logic

---

app/views/record/_extended_info.html.erb
test/integration/record_test.rb

**READY**
Displays all available ISBNs & ISSNs.
We were doing something more complicated but I asked Melissa and she said this is what we do in the status quo so let's keep doing it.
Check out `/record/cat00916a/mit.001712021` on the PR review app. It has multiple ISBNs. The corresponding page on staging has only one.
- https://mitlibraries.atlassian.net/browse/DI-543
NO
NO

Show all available ISBNs/ISSNs per UX advice

---

app/models/button_maker.rb
test/models/button_maker_test.rb

**READY**
The physics department reading room is special, and its items are not
eligible for hold, recall, or scan.
Compare https://mit-bento-staging.herokuapp.com/record/cat00916a/mit.001512948 and the same record in the PR build.
- https://mitlibraries.atlassian.net/browse/DI-572
NO
NO

What happens in the physics room stays in the physics room

---

app/views/search/_result.html.erb

This moves our safe_output function from RecordHelper to
ApplicationController, so that it is available to everybody.
Sharing is caring!
**READY**
Bad:
Good:
`/search/bento?q=TX335.A1.C7581.B9` on the PR build
- https://mitlibraries.atlassian.net/browse/DI-574
NO
NO

Make HTML on search page render rather than display to users

---

app/models/button_maker.rb
test/models/button_maker_test.rb

**HOLD**
I talked through the logic of ticket 513 with people from IDLA. They had a few clarifications about how circ actually works, so I am updating item action rules accordingly.
_Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn_
They're going to be hard to see on a staging server since you would need to know of an item with the correct statuses, and these statuses can be transient.
- https://mitlibraries.atlassian.net/browse/DI-513
- https://mitlibraries.atlassian.net/browse/DI-564
NO
NO

Debug item actions per discussion with IDLA

---

app/helpers/record_helper.rb
app/views/record/_basic_info.html.erb
app/views/search/_result.html.erb
test/helpers/record_helper_test.rb

**READY**
Forces http thumbnails to use https (argh!)
If the url returned from the API is http, it changes it to https. If it is not http, we just use whatever we were given (either https already or something weird. Who knows!)
EDS API returns http thumbnail images. It appears the service they use can handle https. Some browsers are starting to get a bit more vocal with mixed content messages, and there is a desire for this application to avoid that if possible.
In the PR build, do a search and note the images we display in bento view and full record view are using https scheme. The same search in staging will show http scheme.
- https://mitlibraries.atlassian.net/browse/DI-509
NO
NO

Force http thumbnail images to use https

---

app/assets/javascripts/static.js

After disabling GA, watching the console as you click a link (that would normally result in data being sent to GA about what type of link had been clicked), there is a brief flash as the app tries to call the `ga()` function at the end of `TrackLinks()`. Because GA is not present, the function doesn't exist so an error is briefly thrown. The app still functions, but it isn't ideal.
This PR tweaks TrackLinks to check if the `ga()` function exists before calling it - which in local testing eliminates the error.
This was discovered after we removed the GA integration within Bento.
Open production Bento with the developer console open, and click a link on the results page. There should be briefly visible a JS error complaining about an unknown ga function. That same …

Adds check for ga to exist before calling it

---

app/views/record/_sidebar.html.erb

**READY**
Adds feedback link to sidebar of full record. 
- https://mitlibraries.atlassian.net/browse/DI-600
View in PR build: 
https://mit-bento-staging-pr-291.herokuapp.com/record/cat00916a/mit.002342956

add feedback to sidebar

---

app/models/aleph_item.rb
test/integration/record_test.rb
test/models/aleph_item_test.rb
test/vcr_cassettes/record_egregiously_many_items.yml

See ticket for DI-610.
**READY**
Addresses problem where some records were displaying blank (but checked-out) items.
It turns out they weren't items at all, but bogus data returned from our attempt to parse something that was not an item record. The Aleph API only returns 990 items; if there are more than that, then the `<items>` element has a child `<partial>` which warns you that the list has been truncated. Parsing that, while assuming it is an `<item>`, turns out to not really work out for you.
Look at the link in the ticket, on the PR build, and note that it doesn't suck.
- https://mitlibraries.atlassian.net/browse/DI-610
NO
NO

Avoid displaying bogus checked-out item when we exceed Aleph limit

---

app.json
app/assets/stylesheets/_bento.scss
app/controllers/feature_controller.rb
app/helpers/record_helper.rb
app/views/search/bento.html.erb
app/views/search/index.html.erb
config/environments/test.rb
config/features.rb
config/routes.rb
test/features/toggle_fullrecord_test.rb

**READY**
* Adds a feature flagged link to enable another feature. Oh my.
* Provides an in app link to enable the full record displays.
* The intent is that once we are ready and enable this feature, users
will be able to self opt-in / opt-out of the full record displays for
some period of time.
Go to the PR build and click madly on the toggle link (and ideally also confirm the results pages change target URLs as appropriate).
- https://mitlibraries.atlassian.net/browse/DI-609
NO
NO

Adds an in app toggle link to preview full records

---

Gemfile
Gemfile.lock
app/controllers/aleph_controller.rb
app/controllers/record_controller.rb
test/controllers/aleph_controller_test.rb
test/controllers/record_controller_test.rb
test/vcr_cassettes/record_bananas_nonguest.yml

**READY**
- adds caching for eds-api and aleph responses
- this uses ActionCaching
http://guides.rubyonrails.org/caching_with_rails.html#action-caching
While ActionCaching has been removed from Rails core, it is still a
valid and viable solution.
- the eds-api data changes infrequently so caching is likely to speed
up reloads and repeat searches
- the aleph data we really need to be "live" so we cache it with a
shorter expiration. However, most data doesn't change so live-live
is overkill and this will speed up refreshes.
View a full record in the PR build from an on-campus IP. It should take a bit of time to load.
Reload the page and it should be super fast. Yay caching.
From a non-campus IP, reload the same record and it should be slower again the first time but fast again on the second …

Adds caching for eds-api and aleph responses

---

app/views/record/_basic_info.html.erb
test/integration/record_test.rb
test/vcr_cassettes/record_multiple_item_types.yml

Honestly, I have no guarantee here as to the correctness of the data
source here, but it looks like it does the right thing. Resolves DI-624.
**READY**
Sometimes we have an item in multiple formats (e.g. book and ebook). We have been displaying only one, as that is what the EDS API returns. We should display all.
Consult `/record/cat00916a/mit.002379994` on staging and the PR build.
- https://mitlibraries.atlassian.net/browse/DI-624
NO
NO

Allow for multiple publication types to be displayed

---

app/models/button_maker.rb
test/models/button_maker_test.rb

**READY**
User testing revealed that our circ rules are not the same as the ones that had been encoded in bento.
Check the records in the ticket on staging and the PR build. Lo, holds/recalls should be disallowed now.
- https://mitlibraries.atlassian.net/browse/DI-625
NO
NO

Remove ineligible statuses from hold/recall availability

---

app/concerns/sfx_handler.rb
app/helpers/record_helper.rb
app/models/button_maker.rb
app/views/record/_availability.html.erb
app/views/record/_availability_check_online.html.erb
app/views/record/_availability_expiring.html.erb
app/views/record/_availability_full.html.erb
app/views/record/_availability_restricted.html.erb
test/concerns/sfx_handler_test.rb
test/helpers/record_helper_test.rb
test/integration/record_test.rb
test/models/button_maker_test.rb
test/vcr_cassettes/record_omgwtfbbq.yml

* Refactors availability section.
There's already a lot of logic going on in the view to decide what to
show the user under Availability, and DI-607 requires additional logic.
This is too heavy to belong in a view and now lives in the helper.
* Refactors SFX URL generation out of ButtonMaker
We'll need to also access SFX URL generation in record_helper.rb, so it
needs to live in a shared place that understands SFX URL construction
more generally.
* Adds generic SFX link when all other, better-specified, options fail.
* Adds test coverage
**READY**
I'm waiting for Rich to sign off on the format of the generic SFX URLs, but this is ready for code review.
It's theoretically possible that we don't really know if the object is available online. This gives us a fallback option if we are missing …

Provides fallback link to SFX menu if we don't know what else to do

---

app/models/button_maker.rb
test/models/button_maker_test.rb

**READY**
Removes special ILL logic.
There was a time when we felt it was appropriate to try to send people directly to BorrowDirect. It has now been determined that we should always send people to WorldCat where BorrowDirect is one option.
In the ticket there is an example that doesn't actually show the problem anymore so I'm not sure. I suspect the recently merged code that restricted some statuses from ILL prevented the sample record from remaining relevant.
- https://mitlibraries.atlassian.net/browse/DI-628
NO
NO

Removes special ILL logic

---

app/concerns/sfx_handler.rb
app/models/button_maker.rb
test/concerns/sfx_handler_test.rb
test/models/button_maker_test.rb

**READY**
- removes double encoding of passed title and changes to
`URI.encode_www_form_component`
- adds `rft.date` to populate year field
- adds `rft.volume` to populate volume field in the future (changes to
SFX script will be necessary to get this to pass through to Illiad)
On the PR build, activate full record views.
Search for a local record and click "request scan".
The year should be populated and the title should not be encoded.
Confirm on the staging server the same record leads to no year being populated and the title being encoded.
- https://mitlibraries.atlassian.net/browse/DI-618
- https://mitlibraries.atlassian.net/browse/DI-619
- prep for https://mitlibraries.atlassian.net/browse/DI-623
NO
NO

Scan button bug fixes

---

app/views/layouts/_head.html.erb
app/views/record/record.html.erb

**NEEDS REVIEW**
This attempts to allow users to save full records to their Zotero account by adding DC metadata to the head element.
Enable full record, and try to save a full record view via Zotero. This will require you to install the Zotero standalone application and the Zotero extension in the browser of your choice.
- https://mitlibraries.atlassian.net/browse/DI-476
NO
NO

Adds DC metatags for use by Zotero

---

app/models/normalize_eds_common.rb
test/integration/search_test.rb
test/vcr_cassettes/why_only_us.yml

**READY**
Display multiple publication types on the search page when present.
Compare the first result for `/search/bento?q=why+only+us` on the PR build and staging.
- https://mitlibraries.atlassian.net/browse/DI-655
NO
NO

Display multiple item types on search page when present

---

app/helpers/record_helper.rb
app/views/record/record.html.erb
test/helpers/record_helper_test.rb
test/integration/record_test.rb

**READY**
This changes the content for the DC.type meta tag to be a mapped value
from the EDS publication type to the Zotero item type. If no match is
found then the EDS publication type is used.
Find an article with a mapped type like https://mit-bento-staging.herokuapp.com/record/edselp/S0925400517321858. View source and the DC.type should say Journal Article rather than Academic Journal.
- https://mitlibraries.atlassian.net/browse/DI-635
NO
NO

Add DC.type mapping for meta tag

---

app/models/button_maker.rb
test/integration/aleph_test.rb
test/models/button_maker_test.rb
test/vcr_cassettes/record_book_is_on_order.yml

**READY**
Deal with books that are on order - these were displaying a nonfunctioning ILL-request button (because in this case we have enough of a record to construct the full record view, but we don't yet have an OCLC number, so the ILL URL is broken).
The decision (see ticket for discussion) was to do the following:
* remove the ILL button if the ILL URL can't be constructed
* test that the ILL buttonmaker function returns nil if the ILL URL function returns nil
* test that the record display doesn't include any buttons for this Rotch example
There's additional work around the text we should display (in lieu of the inaccurate "Checked out"), but that was split into another ticket.
Compare https://mit-bento-staging.herokuapp.com/record/cat00916a/mit.002579423 to the PR build (assuming the …

631 on order books

---

app/assets/stylesheets/_shame.scss
app/helpers/record_helper.rb
app/views/record/_availability.html.erb
test/helpers/record_helper_test.rb
test/vcr_cassettes/record_journal.yml

**READY**
* extracts summary holdings if they exist
I'll update the review app ENV to point at a test catalog and update info here in a bit.
Just summary holdings (i.e. first entry starts with s_h)
/record/cat01875a/mittest.000285628
Multiple summary holdings and something before it
/record/cat01875a/mittest.000294973
No summary holdings:
/record/cat01875a/mittest.002144417
- https://mitlibraries.atlassian.net/browse/DI-547
NO
NO

Extracts summary holdings for note serial

---

app/assets/stylesheets/_aleph.scss
app/helpers/aleph_helper.rb
app/views/aleph/_list_local_locations.html.erb
test/helpers/aleph_helper_test.rb

**READY**
Limit display of holdings to 99 items and provide link to source for viewing additional records.
A journal record with print holdings is the best example. ex: jama
- https://mitlibraries.atlassian.net/browse/DI-650
NO
NO

Limit aleph holdings displayed

---

app/assets/stylesheets/_aleph.scss

**READY**
Go to full record with holdings and see that the font and line height is adjusted for holdings: 
/record/cat00916a/mit.000294973
- https://mitlibraries.atlassian.net/browse/DI-669

adjust holdings style in full record

---

app/helpers/record_helper.rb
app/views/record/_basic_info.html.erb
app/views/record/_extended_info.html.erb
test/integration/record_test.rb

Testing this feature revealed that the TypePub strategy sometimes
returns nil, so we have a new helper function that uses TypePub info
when present, but falls back to the EDS-supplied publication type
when needed.
**READY**
(per commit message)
Compare https://mit-bento-staging.herokuapp.com/record/cat00916a/mit.001512948 to PR build version of same.
- https://mitlibraries.atlassian.net/browse/DI-681
NO
NO

Make type listed in document type section match that's indicated up top

---

app/helpers/aleph_helper.rb
app/models/aleph_item.rb
app/models/concerns/processing_labeler.rb
app/views/aleph/_list_local_locations.html.erb
test/helpers/aleph_helper_test.rb
test/models/aleph_item_test.rb

**READY**
There may still be some UX review going on, but this is now ready for code review.
Adds status information to "available" / "checked out" indicators to aid decisionmaking. Changes "checked out" to "not available" as there are many reasons items could be unavailable, not just checkouts. Massages the status labels we get from Aleph to improve consistency and readability.
Look at the availability section of your favorite stuff on the PR build. There's a Google doc with examples of stuff with various processing statuses - DM me for the link.
- https://mitlibraries.atlassian.net/browse/DI-658
- https://mitlibraries.atlassian.net/browse/DI-675
- https://mitlibraries.atlassian.net/browse/DI-689
- https://mitlibraries.atlassian.net/browse/DI-690
(All of these tickets involve label text, …

658 processing status

---

app/views/aleph/full_item_status.html.erb
app/views/record/_availability.html.erb

**READY**
- hides sort note by default
- if we have more than 1 holdings item, unhides sort note
Look at records in the PR build with a no local holdings, one local holding item, and more than one local holding item.
- https://mitlibraries.atlassian.net/browse/DI-688
NO
NO

conditionally display sort note

---

app/assets/stylesheets/libraries-global.scss

With the new branding, the MIT logo background covered up the rainbows
and then there was no Pride easter egg and all was woe.
**READY**
Compare https://mit-bento-staging.herokuapp.com/record/cat00916a/mit.002510332 to the same record on the PR build.
- https://mitlibraries.atlassian.net/browse/DI-
NO
NO

Fix super seekrit rainbows feature

---

app/models/custom_hint.rb

**READY**
Google Sheets exports as UTF8. We were not treating the file as UTF8.
I’m not sure why this worked before and didn’t anymore.
The failing record was for Encyclopædia Britannica online which loaded fine with this change on the staging server.
NO
NO

csv was not being treated as utf8

---

app/assets/stylesheets/_bento.scss
app/views/search/_placeholders.html.erb
app/views/search/bento.html.erb

**READY/IN DEVELOPMENT/HOLD**
Adds links to advanced search to the bottom of the Books and Articles boxes. 
- https://mitlibraries.atlassian.net/browse/DI-699
NO
NO

Add adv search links to bottom of books and articles boxes

---

app/controllers/record_controller.rb
app/views/errors/eds_session_error.erb
test/controllers/record_controller_test.rb
test/vcr_cassettes/record_broken_session.yml

- Setting `EDS_DEBUG` will enable the EDS debug mode
- When EDS API is having session issues, the gem fails with a NoMethodError. This detects that and recovers by supplying users an alternative interface link and logs the problem so we can be sure we understand how often this is happening.
NO
NO

Enable ENV toggle-able EDS Debug mode

---

config/puma.rb

**READY**
Enables puma workers and preloads app.
https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server
NO
NO

Enable puma workers and preload app

---

app/views/errors/eds_session_error.erb
test/controllers/record_controller_test.rb

**READY**
Updates some text for a specific failure state on our full records.
The easiest way is to run this locally and change the rescue to a NameError and put a fake variable before it such as `asdf`
- https://mitlibraries.atlassian.net/browse/DI-720
NO
NO

Update text for session errors on full record views

---

app/views/search/_result.html.erb

**READY**
Skip author display if we have no link text.
Ebsco made a change to their API that did something weird. This is just a band aid but it seems fine and returns us to the same behavior we had before.
Search for `orange` in this PR view and the prod site. Prod has a weird author link. This PR does not.
- https://mitlibraries.atlassian.net/browse/DI-746
NO
NO

Suppress author display if we have no link text

---

Gemfile
Gemfile.lock
app/models/search_eds.rb
test/integration/search_test.rb
test/models/search_eds_test.rb

**READY**
Reduces the number of API calls per search significantly by caching tokens.
We currently perform 8 API calls to EDS for every search on our site.
This reduces that number to 2 by caching the Auth Token (EDS Docs suggest caching this for 30 minutes) and session tokens (EDS Docs suggest caching this per user, but for our bento view we have no concept of users so this should be fine... for record view we use their gem and this logic is not in place).
With this we also don't call end session any more as we'll continue to use the session until close to it's expiration time on their end so we'll let them do their own clean up.
TLDR: Once every 25 minutes, a search will require up to 8 API calls like they all do now. Between those times, most searches will require 2 (one for books, one …

cache auth token and session token

---

Gemfile.lock
app/views/record/_basic_info.html.erb

**READY**
Flags titles as safe so ampersands are displayed properly.
Prod:
https://lib.mit.edu/record/edshtl/hvd.32044079556437
Fixed:
https://mit-bento-staging-pr-495.herokuapp.com/record/edshtl/hvd.32044079556437
- https://mitlibraries.atlassian.net/browse/DI-748
NO
NO

Safely display titles in full record view

---

app/assets/stylesheets/_hint.scss

**READY**
Adjusts hint style with new color palette.
Search "lexus" and see hint style. 
Before: 
After:

update hint style

---

app/models/search_eds.rb

**READY**
Stops trying to do a manual encoding of `:` when sending to the EDS API.
I have no record for why this was supposedly needed, but it appears the logic we have is not working so I'm removing this. If this rebreaks something else, we'll at least have a use case documented for why it was needed in the first place.
Search for:
`Bringing Rights Home: Review of the Campaign for a Law on Domestic Violence`
on this PR build and in production.
- https://mitlibraries.atlassian.net/browse/DI-770
NO
NO

Removes special handling for colon

---

.travis.yml

**READY**
Removes a workaround for the bundler version that seems to have been resolved (finally) in the Travis base image.
https://github.com/MITLibraries/bento/commit/ebc8a06097c9593d16445d949931fc839577957d
The travis build works
NO
NO

revert travis bundler install as it seems fine now

---

app/concerns/sfx_handler.rb
app/helpers/record_helper.rb
app/views/record/_availability_check_online.html.erb
test/concerns/sfx_handler_test.rb
test/models/button_scan_test.rb

- uses relevant links from EDS custom links section if they exist and fulltext links is not present. This is the second to last option so it is only used when we'd previously construct an SFX link
- adds rft.stitle to our constructed sfx link fallback if present
The logic behind the links is awful and unfortunately we essentially duplicate it because our initial search does direct API calls and our single record view uses an EDS maintained wrapper gem. At one point a project was proposed to normalize that to always using the wrapper gem but that work was denied. It has been long enough and the effects of that decision are painful enough that it may be appropriate to do that work as routine maintenance.
`/record/edsoro/oro.9780195156003.013.0057`
- …

Prefer custom links to constructed links and improve contructed links

---

Gemfile
Gemfile.lock

**READY**
This removes the apparently-unneeded gem `therubyracer`
https://devcenter.heroku.com/articles/rails-asset-pipeline#therubyracer
The usual way
NO
YES - therubyracer is removed, but I think this happens automatically

removes therubyracer per heroku instructions

---

README.md
app/models/button_hold_recall.rb
app/models/button_scan.rb
config/features.rb

**READY**
This adds 3 features controlled by optional ENV to determine if we will display holds, recalls and scans. Not setting the ENV defaults to the features being on, so we don't need to include these settings in app.json.
View the examples in the linked ticket in prod and the pr build and note the missing buttons in the PR build.
- https://mitlibraries.atlassian.net/browse/DI-827
NO
NO

Allow disabling of hold, recall and scan buttons for local items

---

README.md
app/models/button_ill.rb
config/features.rb

**READY**
This adds the ability to disable ILL buttons controlled by optional ENV. Not setting the ENV defaults to the features being on, so we don't need to include these settings in app.json.
- https://mitlibraries.atlassian.net/browse/DI-827
NO
NO

Allow disabling of ILL buttons for local items

---

app/models/search_timdex.rb
test/models/search_timdex_test.rb
test/vcr_cassettes/quoted_timdex.yml

This was the easiest way to avoid the double quote issue in our
GraphQL syntax.
**READY**
Search on production for a quoted term that has double quotes.
Search on this PR build for the same term.
This one should work.
- https://mitlibraries.atlassian.net/browse/ENGX-13
NO
NO

Changes double to single quotes for timdex search

---

app/controllers/record_controller.rb
app/views/record/not_found.erb
test/controllers/record_controller_test.rb

**READY**
For some reason we were sending exceptions on every invalid record request. We also sent 404 status but throwing an exception was not appropriate here so this removes that.
Locally, check out the master branch and request an invalid record such as:
localhost:3000/record/cat00916a/mit.fake
Note the exceptions in the logs.
Check out this branch and request the same record. You should see no exceptions logged.
- https://mitlibraries.atlassian.net/browse/ENGX-44
NO
NO

Don't throw exceptions on no record found

---

app/models/button_aeon.rb
test/models/button_aeon_test.rb

**READY**
Changes the link text for Aeon requests from 'Order a copy' to 'Order/get a copy'.
Check a record with an Institute Archives/Distinctive Collections holding, e.g.: https://mit-bento-staging-pr-723.herokuapp.com/record/cat00916a/mit.000583269
The button to the right of 'Order for on-site use' should read 'Order/get a copy'.
- https://mitlibraries.atlassian.net/browse/UXWS-986
NO
NO

Change language for Aeon button link text

---

README.md
app/models/button_hold_recall.rb
test/integration/aleph_test.rb
test/models/button_hold_recall_test.rb

Adds configurable Aleph UI host name so we can test links to non-production system.
Updates wording to not reflect the time to place a Hold.
- https://mitlibraries.atlassian.net/browse/DI-874
NO
NO

Allow UI links to test aleph and update hold button wording

---

app/models/button_hold_recall.rb
test/integration/aleph_test.rb
test/models/button_hold_recall_test.rb

Stakeholders requested a small wording change to match the button that provides the same functionality in Aleph.
Partial work towards
https://mitlibraries.atlassian.net/browse/DI-874
- https://mitlibraries.atlassian.net/browse/DI-874
NO
NO

Update hold button wording to match Aleph

---

README.md
app/models/button_hold_recall.rb
app/models/button_maker.rb

**READY**
Adjust logic for Hold buttons based on stakeholder feedback.
- Ensures Hold buttons are not displayed for renovation affected items even if WorldCatinator feature is disabled
- Allows Holds on any item status if Recalls are disabled
There are example records in the linked ticket, but mostly we need to check with stakeholders for edge case detection to know for sure if this is 🌈 
- https://mitlibraries.atlassian.net/browse/DI-917
NO
NO

Hold button tweaks

---

README.md
app/models/search_primo.rb
config/environments/test.rb
db/schema.rb
test/models/search_primo_test.rb
test/test_helper.rb
test/vcr_cassettes/bad_primo_response.yml
test/vcr_cassettes/popcorn_primo.yml

With the Primo launch forthcoming, we need to update Bento to query the
Primo Search API.
* https://mitlibraries.atlassian.net/browse/IMP-1871
This introduces a Primo Search model, which includes some rudimentary
logic to call the Primo Search API, and updates the readme accordingly.
* The db schema timestamp updated in a weird way, as a result of my
having to run migrations locally.
* There are two new VCR cassettes: one for a normal Primo search, and
one for a bad Primo API response.
* Various API params have been added to ENV. Notably, PRIMO_VID_INST
is actually two params (see the changes to the readme for more info).
issues (link to those …

Add Primo Search model

---

README.md
app/models/search_primo.rb
config/environments/test.rb
test/models/search_primo_test.rb
test/test_helper.rb
test/vcr_cassettes/popcorn_primo_articles.yml
test/vcr_cassettes/popcorn_primo_books.yml

Our current implementation of the Search Primo model does not allow us
to scope searches to Alma or CDI.
* https://mitlibraries.atlassian.net/browse/IMP-1961
This adds a `scope` parameter to the query string constructor in the
Search Primo model, into which we can pass the `alma` (Books+) or
`cdi` (Articles+) scopes. These scopes are implemented as ENV variables,
so we can change them as needed. It also changes the tab to the new
`bento` tab, which isn't strictly necessary but could save us trouble
in the future.
* The `inst` query param, which is not required for hosted customers, has
been removed, and the variable name changed from `PRIMO_VID_INST` to
`PRIMO_VID`.
* Removed the `popcorn_primo` cassette and added scoped cassettes
(`popcorn_primo_articles` and `popcorn_primo_books`).
[our …

IMP-1961 Enable scoped Primo searches

---

README.md
app/models/normalize_primo_articles.rb
app/models/normalize_primo_books.rb
app/models/result.rb
config/environments/test.rb
test/models/normalize_primo_articles_test.rb
test/models/normalize_primo_books_test.rb
test/models/result_test.rb
test/vcr_cassettes/missing_fields_primo_articles.yml

If a resource is available online, a user should be able to access
the full text from the Bento record.
* https://mitlibraries.atlassian.net/browse/IMP-2008
This renders full-text/Get It links when available for Alma and CDI
results. For Alma results, we construct an Alma link resolver URL if the
resource is tagged as 'Alma-E'. CDI results already have these URLs in
the API response, so we can pull them directly from the JSON.
Because some Alma records are not yet linked to their eresources, certain
'Get It' links will not be proxied. This is a known issue and is being
actively investigated.
issues (link to those issues in the Pull Request …

Add 'Get It' links for Primo results.

---

app/controllers/search_controller.rb
app/models/search_primo.rb
app/views/search/bento.html.erb
config/features.rb
test/models/normalize_primo_articles_test.rb
test/models/normalize_primo_books_test.rb
test/models/normalize_primo_test.rb
test/models/search_primo_test.rb
test/vcr_cassettes/local_journal_primo.yml
test/vcr_cassettes/missing_fields_primo.yml
test/vcr_cassettes/missing_fields_primo_articles.yml
test/vcr_cassettes/missing_fields_primo_books.yml
test/vcr_cassettes/missing_fields_primo_chapter.yml
test/vcr_cassettes/no_results_primo.yml
test/vcr_cassettes/physical_book_primo.yml
test/vcr_cassettes/popcorn_primo.yml
test/vcr_cassettes/popcorn_primo_articles.yml
test/vcr_cassettes/popcorn_primo_books.yml
test/vcr_cassettes/primo_chapter.yml

We will be replacing EDS with Primo, so our Bento search should display
results from the Primo Search API.
* https://mitlibraries.atlassian.net/browse/IMP-1776
* Uses primo_search feature flag to conditionally display Primo search
results.
* Adds limit param to Primo search so we can control the number of
results in the Bento view.
* All VCR cassettes for tests related to the Primo Search API have
been regenerated due to the new param.
* The PRIMO_SEARCH env variable is now type cast as a boolean to allow
for clearer enabling/disabling of the feature flag. (I.e., if it is set
to true, Bento returns Primo results; if set to false, Bento returns
EDS results).
all issues introduced by these changes have been resolved or …

IMP-1776 Render Primo search results in Bento view

---

app/models/normalize_primo_articles.rb
app/models/normalize_primo_books.rb
test/models/normalize_primo_articles_test.rb
test/models/normalize_primo_books_test.rb

* Full-text links for CDI records lead to a disambiguation page with no
styling.
* Some records' links include a link to the eresource's table of contents,
but not to the full-text.
* https://mitlibraries.atlassian.net/browse/IMP-2008
* Modifies the openurl call in the `almaOpenUrl` field to redirect to the
Primo UI.
* Adds `u.ignore_date_coverage` param to all openurl links so full-text
links display instead of ToC links.
This assumes consistency in the `almaOpenUrl` field in the Primo Search API response. If a CDI record does not have the standard base URL in this
field, then the full-text link will likely fail.
issues (link to those issues …

Implement stakeholder feedback for IMP-2008

---

app/models/normalize_primo_common.rb
test/models/normalize_primo_test.rb
test/vcr_cassettes/monkeys_primo_articles.yml

The Primo API occasionally provides multiple author names in a single
array element. The Primo normalization code reads this as a single author
name and generates a single link to the Primo author browse results,
instead of one link per author. This bug was identified during UX revivew
of IMP-1953.
* https://mitlibraries.atlassian.net/browse/IMP-1953
This adds some logic to our author sanitization code to look for more
bad data and attempt to fix it.
None, but there are likely more examples of bad Ex Libris data requiring
remediation that we've yet to find. We will continue to push bug fixes
and add regression testing as needed.
issues (link to …

Fix bug that generates a single link for all authors in some instances

---

app/models/normalize_primo_books.rb
test/models/normalize_primo_books_test.rb

Relevance in the Primo subject browse is poor for queries that include
hyphens. This is a problem because compound subjects in library metadata
are divided with hyphens.
* https://mitlibraries.atlassian.net/browse/IMP-2056
This removes hyphens from compound subject links.
We are still displaying hyphens in the UI, so there's a risk for
confusion when the linked Primo subject browse query is punctuated
differently.
NO
NO

IMP-2055 Remove hyphens from subject links

---

README.md
app/controllers/search_controller.rb
app/helpers/search_helper.rb
app/models/normalize_primo.rb
app/models/search_primo.rb
app/views/search/_result.html.erb
app/views/search/bento.html.erb
config/environments/test.rb
test/integration/search_test.rb
test/models/normalize_primo_articles_test.rb
test/test_helper.rb
test/vcr_cassettes/local_journal_primo.yml
test/vcr_cassettes/missing_fields_primo.yml
test/vcr_cassettes/missing_fields_primo_articles.yml
test/vcr_cassettes/missing_fields_primo_books.yml
test/vcr_cassettes/missing_fields_primo_chapter.yml
test/vcr_cassettes/monkeys_primo_articles.yml
test/vcr_cassettes/no_results_primo.yml
test/vcr_cassettes/physical_book_primo.yml
test/vcr_cassettes/popcorn_primo.yml
test/vcr_cassettes/popcorn_primo_articles.yml
test/vcr_cassettes/popcorn_primo_books.yml
test/vcr_cassettes/primo_chapter.yml

The 'view more books' and 'view more articles' links don't work properly
because the tab and scopes we use in Bento aren't enabled in the Primo
UI. Darcy, Adam Shire, and I discussed the problem and decided to continue
using the 'bento' tab, but enable the 'cdi' search scope in Primo, and
use a 'catalog' scope for local results instead of Alma.
* https://mitlibraries.atlassian.net/browse/IMP-2055
* Removes hardcoding of search scopes and tabs in anticipation of
potential future name changes.
* Updates hardcoded scope names in the app where necessary.
* Adds PRIMO_MAIN_VIEW_TAB ENV variable, corresponding to Primo UI tab.
* Adds PRIMO_TAB ENV variable, corresponding to Bento tab.
* Changes existing Primo API ENV variables to more closely reflect their
actual functions (e.g., …

IMP-2055 Update Primo API scopes and fix 'view more' links

---

app/models/normalize_primo_common.rb
config/environments/test.rb
test/models/normalize_primo_test.rb

Primo browse search does not include CDI results, which will be
confusing for Bento author links, especially when clicking an author link
on a CDI record.
* https://mitlibraries.atlassian.net/browse/IMP-2072
This reverts back to using regular Primo searches instead of browse
searches for author links.
We are using the `exact` operator instead of `contains`, so the linked
search will include fewer results (but will be more accurate).
NO
NO

IMP-2072 Change author links to regular searches

---

app/assets/stylesheets/_results.scss
app/models/normalize_primo_books.rb
app/models/result.rb
app/views/search/_result.html.erb
test/models/normalize_primo_books_test.rb
test/models/result_test.rb
test/vcr_cassettes/physical_book_primo.yml

Our original plan was to use the Alma Bib API for RTA, but we are
considering whether a more lightweight option using the Primo Search API
is viable. This scaled back version of RTA will tell users whether any
physical copy is available for a given result.
* https://mitlibraries.atlassian.net/browse/IMP-2093
* Updates the normalize_primo_books model to pull availability status
from catalog records and pass it into the result model.
* Adds availability? method to the result model that determines whether
any copies of a result are available for checkout.
* Adds check_holdings? method to the result model, which corresponds
with partial/unclear availability (e.g., one or more volumes is checked
out).
* Updates result view to display availability status.
Minor CSS changes to clean up display …

IMP-2093 Display record-level real-time availability

---

app/assets/stylesheets/_results.scss
app/models/normalize_primo_books.rb
app/models/result.rb
app/views/search/_primo_rta.html.erb
app/views/search/_result.html.erb
test/models/normalize_primo_books_test.rb
test/models/result_test.rb
test/vcr_cassettes/multi_available_book_primo.yml
test/vcr_cassettes/partially_available_book_primo.yml
test/vcr_cassettes/physical_book_primo.yml
test/vcr_cassettes/unavailable_book_primo.yml

This introduces changes requested during UX review of our initial
RTA iteration.
* https://mitlibraries.atlassian.net/browse/IMP-2120
* Displays only one location (the 'best location' as determined by
Alma/Primo), instead of every location where the item is held.
* Refactors availability status logic accordingly. The app now displays
'best location' availability and indicates whether the item is available
in other locations.
* Adds requested CSS updates.
* Changed newlines for attr_accessor in the result model. This is purely
aesthetic to keep line width reasonable, but it might make it hard to
see the changes: `availability` and `other_availability` were added, and
`availability_status` was removed.
* Two new cassettes:
* partially_available_book_primo
* unavailable_book_primo
* Reverts …

Implement revised UI for Primo real-time availability

---

app/views/layouts/_site_footer.html.erb

A link in the footer goes to a WP page that will be removed after we
launch Primo.
https://mitlibraries.atlassian.net/browse/IMP-2176
This removes the link that is no longer needed.
None.
NO
NO

IMP-2176 Remove 'Learn more' link from footer

---

README.md
app/controllers/record_controller.rb
config/environments/test.rb
config/features.rb
test/controllers/record_controller_test.rb
test/integration/record_test.rb
test/integration/search_test.rb
test/vcr_cassettes/sru_article.yml
test/vcr_cassettes/sru_book.yml
test/vcr_cassettes/sru_journal.yml

Bento full record links are occasionally used as permalinks, but we will
be turning them off once we launch Primo.
https://mitlibraries.atlassian.net/browse/IMP-2007
This adds logic to the record controller, toggled by a feature flag,
that makes an Alma SRU query for Aleph record and determines whether we
can unambiguously link to a corresponding record in Primo (i.e., the SRU
returns one and only one record). If we can, we redirect users to that
Primo record, and if not, we redirect them to a generic splash page that
describes the switch from EDS to Primo.
We now toggle feature flags in the test environment using Flipflop's
built-in :test strategy.
all issues introduced by these changes have been resolved or opened …

Add feature flag to redirect full record links to Primo

---

app/views/search/_primo_rta.html.erb

Usability testing revealed that 'check options' does not clearly reveal
the purpose of this link.
https://mitlibraries.atlassian.net/browse/IMP-2199
This changes the link text from 'check options' to 'check request options'.
None
NO
NO

Update request options link text

---

app/models/normalize_primo_books.rb
test/models/normalize_primo_books_test.rb

The subject browse feature in Primo is ineffectual.
https://mitlibraries.atlassian.net/browse/IMP-2239
Subject links are now Primo searches with the `subject,exact` operators
rather than the subject browse.
None, although the search term highlighting in Primo is a bit misleading.
NO
NO

IMP-2239 Use search instead of browse for subject links

---

app/views/search/_view_all_link.html.erb

The 'view more' links for website/Google and ArchivesSpace searches break
when the Primo feature flag is toggled due to a flawed conditional in
the view_all_links partial.
https://mitlibraries.atlassian.net/browse/IMP-2240
This adjusts the aforementioned conditional to check if the Primo feature
flag is enabled AND if the target param is equal to one of the two Primo
targets.
None.
NO
NO

IMP-2240 Fix 'view more results' URLs when Primo searches are enabled

---

app/assets/stylesheets/_results.scss

When it can't find a cover image, Syndetics returns a 1x1 pixel JPEG. We
look for cover images for anything with an ISBN, so the app will often
incorrectly render a 'cover image' (i.e., a 1x1 dot) for books that
don't have one. This results in a weird-looking border surrounding
seemingly nothing.
https://mitlibraries.atlassian.net/browse/IMP-2241
Removes the border from cover images.
Cover images no longer have border, so they are very slightly less
prominent.
NO
NO

IMP-2241 Remove borders from cover images

---

README.md
app/models/search_eds.rb
app/models/search_timdex.rb
test/models/search_timdex_test.rb

Why these changes are being introduced:
Currently only EDS searches time out. We want to make sure we catch
timeouts on the other search models as well.
https://mitlibraries.atlassian.net/browse/IMP-2236
How this addresses that need:
Adds a timeout to the TIMDEX search model.
Side effects of this change:
TIMDEX timeouts should now raise an HTTP::TimeoutError, which should
in turn get caught by Sentry. If this becomes troublesome, we can adjust
Sentry's settings to make these alerts less noisy.
NO
NO

IMP-2236 Add timeouts to TIMDEX search model

---

README.md
app/models/search_primo.rb
test/models/search_primo_test.rb

Currently only EDS searches time out. We want to make sure we catch
timeouts on the other search models as well.
https://mitlibraries.atlassian.net/browse/IMP-2235
Adds a configurable timeout to the Primo search model.
Primo timeouts should now raise an HTTP::TimeoutError, which should
in turn get caught by Sentry. If this becomes troublesome, we can adjust
Sentry's settings to make these alerts less noisy.
NO
NO

IMP-2235 Add timeouts to Primo search model

---

app/assets/stylesheets/_results.scss
app/controllers/search_controller.rb
app/helpers/search_helper.rb
app/models/normalize_primo.rb
app/models/normalize_primo_books.rb
app/models/result.rb
app/views/search/_primo_rta.html.erb
app/views/search/_result.html.erb
test/integration/search_test.rb
test/models/normalize_primo_books_test.rb
test/vcr_cassettes/beloved_primo.yml
test/vcr_cassettes/popcorn_primo_books.yml

Since launch, we've enabled FRBR/dedup records in Primo. We would
also like to display this information in Bento.
https://mitlibraries.atlassian.net/browse/IMP-2262
This checks the FRBR/dedup status of catalog records. If a record
is dedup, a link to the other versions will be displayed in the result
instead of the RTA info.
The ticket for this work mentions a stub record. For this first
iteration, I've removed only the result type in order to reflect the
Primo UI more closely, and the RTA info to reduce confusion about
availability. More or less info can be removed pending stakeholder
review.
Removes a bit of CSS that is not needed.
issues …

IMP-2262 Display dedup status in result view

---

app/controllers/search_controller.rb
test/integration/search_test.rb

The Search Controller contains some confusing logic with regard to
validating the target param. The controller checks the target param
against an array of 'valid' targets; if the target is not
considered valid, the controller returns a redirect to the root URL.
This is problematic for a few reasons:
1. It's not very maintainable. We will have to modify the hardcoded
array of valid targets whenever the value of the param, which is stored
in ENV, changes. We've already encountered this with faked param values
in our test suite.
2. It's not very usable. If a user enters a bad param, redirecting
them to the root URL doesn't tell them anything useful about what
went wrong.
3. It's not very intuitive. We already have a method that checks for
which type of search to run based on the target …

IMP-2283 Remove target validation from Search Controller

---

app/controllers/record_controller.rb

We currently only guard against :an params that don't start with 'mit',
which means the application throws a NoMethodError if that param is nil.
https://mitlibraries.atlassian.net/browse/ENGX-102
This adds a guard clause to RecordController#alma_sru to check if
params[:an] is present.
None.
YES | NO
YES | NO

ENGX-102 Guard against nil :an param in record controller

---

app/models/normalize_primo_common.rb

The November release of Primo VE unexpectedly broke our 'Details
and requests' links, which are constructed as Primo fulldisplay
'deep links'. In the latest release, Ex Libris made two params
(`context` and `search_scope`) required for fulldisplay links.
This was most likely accidental as the change is not mentioned in
the release notes, and the params are not required consistently:
i.e., `context` is required only for local records, and
`search_scope` is required only for CDI records.
https://mitlibraries.atlassian.net/browse/IMP-2358
This adds to our 'Details and requests' links all of the params
included in the Ex Libris docs' fulldisplay example link:
https://developers.exlibrisgroup.com/primo/apis/deep-links-new-ui/
In reality, not all of these params are required, but hopefully …

IMP-2358 Bugfix for 'Details and requests' links

---

app/models/normalize_primo_articles.rb
test/models/normalize_primo_articles_test.rb

Why these changes are being introduced:
Some Primo openurls do not resolve correctly. The Alma/Primo team
suspects that the cause is the ctx params in the URL.
https://mitlibraries.atlassian.net/browse/ES-572
How this addresses that need:
This removes the ctx params from the Primo openurls.
Side effects of this change:
I have some reservations about how much we're manipulating URL
strings here. If this fixes the problem, we should have a
conversation about this in code review.
NO
NO

ES-572 Primo openurl bugfix

---

.codeclimate.yml

* CodeClimate uses an older version of Rubocop internally by default,
but this can be updated using a .codeclimate.yml file.
* n/a
* This adds the needed configuration file, using the same version that
we are using for the Timdex* projects.
* This version will need to be updated down the road, ideally in sync
with our other repos and as new versions of Rubocop become available.
There is no mechanism to detect how out of date this is, however...
* As with our other updates to this channel, any changes to the codebase itself are out of scope for this PR.
NO
NO (not this codebase, just a configuration to an associated platform)

Adds .codeclimate.yml to update rubocop

---

app/views/hint/hint.html.erb

Why these changes are being introduced:
We are moving from GetURLs to LibGuides for our friendly URLs.
https://mitlibraries.atlassian.net/browse/UXWS-1371
How this addresses that need:
This updates the hint partial to render URLs that include
'libguides.mit.edu'.
Side effects of this change:
GetURLs will no longer render in the hints panel.
NO
NO

Update hints view to render libguides URLs

---

app/models/normalize_timdex.rb
test/models/normalize_timdex_test.rb
test/vcr_cassettes/aspace_multiple_creation_dates.yml
test/vcr_cassettes/aspace_publication_date.yml

We encountered a bug after V2 launch in the normalization process, during which Bento hits an unhandled nil value that breaks the search results. This is because we are assuming every ASpace record has a creation date, when in fact some of them have publication dates instead.
Somewhat related to this is a transmogrifier bug that causes a `kind` to be associated with a date even when there is no date.
* https://mitlibraries.atlassian.net/browse/TIMX-211
* https://mitlibraries.atlassian.net/browse/TIMX-212
This updates `NormalizeTimdex#extract_dates` to select as relevant dates of either the 'creation' _or_ 'publication' date kind. It also adds a guard clause to return if the `relevant_dates` array is empty (a precaution that would have prevented this error).
I removed a superfluous check …

Better error handling for dates

---

app/models/normalize_timdex.rb
test/models/normalize_timdex_test.rb
test/vcr_cassettes/aspace_nil_dates.yml

It's possible that a result may have a `dates` value of `nil`. This is not currently handled in the
TIMDEX normalization model.
https://mitlibraries.atlassian.net/browse/TIMX-219
This adds a guard clause for nil dates to NormalizeTimdex#extract_dates.
Some style changes were made by rubocop to unrelated tests.
NO
NO

Handle nil dates in TIMDEX searches

---

Gemfile
Gemfile.lock
README.md

The GDT project added a feature to the theme gem to conditionally include the platform name in the header if the `PLATFORM_NAME` environment variable is supplied.
https://mitlibraries.atlassian.net/browse/GDT-124
This updates the theme gem to the v1.2 tag, which includes the new feature, and documents the PLATFORM_NAME variable.
None. The app will continue to use the standard header if PLATFORM_NAME is not supplied.
NO
YES

Update theme gem and document PLATFORM_NAME variable

---

README.md
app/views/search/_trigger_tacos.html.erb
app/views/search/bento.html.erb

This defines a new env variable, TACOS_URL, which stores the endpoint
for the TACOS GraphQL service. When defined, the search results page
will then direct the user agent to send the search string to the TACOS
system, which will eventually respond with any additional information
we can detect about the search string.
For now, the only response will be to reflect the search string back
into the console, along with the originating system.
- https://mitlibraries.atlassian.net/browse/ENGX-267 (this change to Bento)
- https://mitlibraries.atlassian.net/browse/ENGX-266 (the related TACOS change to CORS behavior)
issues (link to those issues in the …

Initial TACOS integration

---

README.md
app/assets/stylesheets/_survey.scss
app/assets/stylesheets/application.scss
app/views/search/_nps_feedback.html.erb
app/views/search/bento.html.erb

Why are these changes being introduced:
* UX has requested this to gather feedback from users
* https://mitlibraries.atlassian.net/browse/PW-102
How does this address that need:
* Creates display panel that is configured via ENV to allow for making changes to content without redeploys of code
Document any side effects to this change:
* Added some newish sqlite files to gitignore
NO
NO

Adds panel for NPS surveys

---

Gemfile.lock

I had temporarily prevented sqlite from installing because it will fail until we upgrade Rails. Because we've enabled the frozen config in bundler, Heroku builds won't work until this is either removed from Gemfile.lock or added to the Gemfile. I'd prefer not to add it to the Gemfile, because we might then forget to upgrade the gem when we upgrade Rails.
YES | NO
YES | NO

Remove sqlite version requirement

---

app/models/normalize_primo_common.rb
test/models/normalize_primo_test.rb

Why are these changes being introduced:
* Author linking does not encode the author names which sometimes made the links to Primo not work as expected
* https://mitlibraries.atlassian.net/browse/PW-132
How does this address that need:
* Encodes the author component of the URL
Document any side effects to this change:
I didn't look at anything else as we so rarely touch this code I don't remember how a lot of it works and I didn't want to pull strings that caused much more work than we intended at this time.
NO
NO

Update Primo author link encoding

---

renovate.json

Why are these changes being introduced:
* Ruby and Rails should keep versions in line with recommendations
* This pins Ruby to version 3.2.x and Rails to 7.1.x
* When we upgrade to Rails 7.2, we will bump Ruby to 3.3

Restrict ruby and rails upgrades
