MITLibraries/bento

app/models/search_eds.rb, app/views/search/bento.html.erb, test/models/search_eds_test.rb, test/vcr_cassettes/article_results_with_no_book_results.yml, test/vcr_cassettes/no_results.yml
=> Handles no results from query

app/controllers/search_controller.rb, test/controllers/search_controller_test.rb, test/integration/search_test.rb
=> Ensures search term is present

app/models/search_eds.rb, app/views/search/search.html.erb, test/models/search_eds_test.rb, test/vcr_cassettes/rollbar8.yml
=> Handle eds results with no year

app/models/search_eds.rb, app/models/search_google.rb
=> Removes raw results from search results

Gemfile.lock, README.md, db/schema.rb
- Removes license badge since Github has a license link now for the
repo directly.
- Adds CodeClimate badge
=> Update deps and readme

README.md, app.json, app/models/normalize_worldcat.rb, app/models/result.rb, app/views/search/_result.html.erb, config/environments/test.rb, test/models/result_test.rb
=> Truncate long author lists

app/models/normalize_eds.rb, test/models/normalize_eds_test.rb, test/vcr_cassettes/popcorn_books.yml
* this handles bug when no authors are present during sfx url creation
https://mitlibraries.atlassian.net/browse/DI-123
* also includes a test for falling back to "unknown title". that will
get more complicated soon, but for now it's good enough.
=> Handle sfx url generation with no authors

app/assets/javascripts/bootstrap.js
One file got left behind when I removed bootstrap.
=> remove old js file

app/assets/stylesheets/bento.scss, app/views/layouts/_head.html.erb, app/views/layouts/_site_header.html.erb
Changes site and page title to "Discovery search" - addresses [DI-149](https://mitlibraries.atlassian.net/browse/DI-149)
=> adjust site title and page title

app/assets/stylesheets/bento.scss, app/assets/stylesheets/libraries-global.css
=> make global notice dark

app/assets/stylesheets/bento.scss, app/assets/stylesheets/libraries-global.css
Minor improvement to make the items a little easier to digest as blocks.
=> Adds hover state for items

app/views/layouts/_about-bento.html.erb, app/views/layouts/_breadcrumbs.html, app/views/layouts/_global_alert.html.erb, app/views/layouts/_institute_footer.html.erb, app/views/layouts/_site_footer.html.erb, app/views/layouts/_site_header.html.erb, app/views/layouts/application.html.erb, app/views/search/_result.html.erb, app/views/search/bento.html.erb
This PR adjusts code and content to make a decent base experience for screenreaders (more nuanced improvements to follow). Changes include adding landmarks and aria labels, adding breadcrumbs, checking color contrast, adding context to content (eg. label "Authors" for author list), checking navigability using NVDA. Passed webaim wave test.
=> Base a11y improvements

app/assets/stylesheets/bento.scss, app/assets/stylesheets/libraries-global.css, app/views/layouts/_site_footer.html.erb, app/views/layouts/application.html.erb, app/views/search/bento.html.erb
This PR adds pagination styles and breadcrumbs, and adjusts some visual styles (more boxiness and colors).
=> View more pagination and style adjustments

app/views/search/search_boxed.html.erb
* adds page heading and sidebar to view more results views
* see also https://mitlibraries.atlassian.net/browse/DI-151
Note: this is a bit kludgy and needs to styles work, but should allow us
to confirm this is what we want
=> Adds sidebar to view more results views

app/views/search/bento.html.erb
* Passes current searchterm to worldcat to jumpstart the search
=> Updates link to worldcat to jumpstart search

app/assets/stylesheets/libraries-global.css, app/views/search/bento.html.erb
Shrink breadcrumb padding and match box links and headers.
=> Small adjustments

app/assets/stylesheets/bento.scss, app/views/search/_help.html.erb, app/views/search/_other_resources.html.erb, app/views/search/bento.html.erb
This PR makes a few small changes in response to the feedback from testing (and in prep for the next round of testing).
=> Text changes and hide source (for now)

app/assets/stylesheets/bento.scss, app/views/search/_result.html.erb
https://mitlibraries.atlassian.net/browse/DI-192
=> Adds Published year to book results

app/assets/stylesheets/bento.scss
=> adjust cover and button alignment

app/assets/stylesheets/bento.scss, app/views/search/_result.html.erb, app/views/search/bento.html.erb
This PR contains a few small changes that came out of testing: 
- make bento lighter
- make titles look more like links
- add text about sorting by relevance
- put worldcat link on a new line
- move year next to type in books
=> small changes from testing

app/assets/stylesheets/bento.scss, app/views/search/search_boxed.html.erb
removes white lines on sides of items and adds white hover.
=> view more style fixes - resolves #124

app/assets/stylesheets/bento.scss, app/views/feedback/index.html.erb, app/views/feedback/submit.html.erb, app/views/layouts/application.html.erb, app/views/search/bento.html.erb, test/integration/feedback_test.rb
This PR styles the feedback link, form, and thanks page.
=> Style feedback

app/models/normalize_eds_articles.rb, app/views/search/_result.html.erb, test/models/normalize_eds_articles_test.rb
This PR removes links to journal titles (https://mitlibraries.atlassian.net/browse/DI-212).
=> Remove journal title links

app/assets/stylesheets/bento.scss, app/controllers/application_controller.rb, app/models/normalize_eds_common.rb, app/models/result.rb, app/views/search/_result.html.erb, config/routes.rb, test/controllers/application_controller_test.rb
* adds a debug mode toggled via `/debug`
* moves db source from hidden css to debug mode
* adds both constructed and extracted links so staff can decide which
links are best in various situations
=> Debug mode and links to consider

app/assets/javascripts/static.js, app/views/layouts/_head.html.erb, app/views/search/_other_resources.html.erb, app/views/search/_placeholders.html.erb, app/views/search/_result.html.erb, app/views/search/_view_all_link.html.erb, app/views/search/bento.html.erb
This changes our analytics approach to achieve two goals:
1) Recording of additional interactions (increased scope)
2) Recording of relevant context (less detail)
=> Better analytics

app/assets/stylesheets/bento.scss, app/views/layouts/_about-bento.html.erb, app/views/search/_help.html.erb, app/views/search/_other_resources.html.erb, app/views/search/bento.html.erb
This PR makes some small changes before we release to staff: 
- adjust other resource links
- update text in a few places
=> small pre-staff release fixes

app/models/normalize_eds_articles.rb, app/models/normalize_eds_books.rb, app/models/normalize_eds_common.rb, app/models/result.rb, app/views/search/_result.html.erb, test/models/normalize_eds_articles_test.rb, test/models/result_test.rb
What:
* Extracts an additional link of interest
* Prioritizes "best" link as `getit_url`. This is likely to need
adjustment over time
Why:
* The additional link we are extracting is the best link available
for many records
=> Expands options and prioritizes of links

app/views/layouts/_head.html.erb, app/views/layouts/application.html.erb, config/application.rb, config/environments/production.rb
What:
* compress text-like assets
* long expiration on static assets
Why:
* pagespeed recommendations
=> Production performance tweaks

app/views/search/search_boxed.html.erb
Adds a class to the result count on the in-app view more pages so it's a little more laid back.
=> add class to result count on view more page

app/assets/stylesheets/libraries-global.scss
This PR updates the global libraries style css to include green buttons and update the global notice styles to be less ugly.
=> add green buttons and update global notice styles

app/controllers/search_controller.rb, app/views/search/_view_all_link.html.erb
What:
* Only displays the view more link for a box when there are more results
to show than fit in the box
https://mitlibraries.atlassian.net/browse/DI-265
=> Hide view more link when not relevant

app/views/search/_result.html.erb
This PR changes the wording on the online button to make it more obvious that it is a button that gets the online thing.
=> Change online button to action

app/assets/stylesheets/libraries-global.scss
adds a few new styles and removes old prefixes.
=> Update global css

app/assets/stylesheets/_results.scss, app/models/normalize_eds_common.rb, app/models/result.rb, app/views/search/_result.html.erb, test/models/normalize_eds_test.rb, test/vcr_cassettes/ultimate_hitchhiker.yml
What:
* Extracts and displays uniform title if available for book and
article results
Why:
* The uniform title often has important information to convey
https://mitlibraries.atlassian.net/browse/DI-113
=> Extracts and displays uniform title if available

app/models/normalize_eds_books.rb, app/models/normalize_eds_common.rb, test/models/normalize_eds_test.rb, test/vcr_cassettes/historico.yml
What:
* some data that we expected to always be present is not always present
in eds responses so we now have checks to prevent errors from
occurring when that situation arises
https://mitlibraries.atlassian.net/browse/DI-312
=> Handle missing bibentity data

app/assets/stylesheets/_bento.scss, app/views/search/_other_resources.html.erb
This PR adds an informational well beneath the books and articles boxes that gives a bit more info about what may not show up in the results.
=> Informational well

app/views/search/_other_resources.html.erb
The PR updates the content of the Other box from team feedback.
=> Update other box content

app/views/search/_view_all_link.html.erb
The view all button should be a primary button not a secondary one.
=> make view all button primary blue

app/helpers/search_helper.rb, app/views/search/_view_all_link.html.erb
What:
* updates view more links to reference the type of link and remove
the number of results from the link text
https://mitlibraries.atlassian.net/browse/DI-348
=> Updates view more links

app/mailers/feedback_mailer.rb, test/controllers/feedback_controller_test.rb, test/integration/feedback_test.rb, test/mailers/feedback_mailer_test.rb
https://mitlibraries.atlassian.net/browse/DI-368
=> Updates feedback email subject

app/models/normalize_eds_common.rb
BugFix for https://mitlibraries.atlassian.net/browse/DI-392
=> Handle EDS records with no BibRelationships

app/controllers/search_controller.rb
https://mitlibraries.atlassian.net/browse/DI-393
1500 seems like a good value, but `ENV['MAX_QUERY_LENGTH’]` is
available to override without having to change the code.
=> bug fix for long search terms

app/models/normalize_eds_articles.rb
reported via: https://rollbar.com/mit-libraries/bento/items/79/
=> bugfix: recover from missing bib data

app/assets/stylesheets/_variables.scss
Updates the sass variables from the mitlib style-guide.
=> update sass variables

app/assets/stylesheets/_bento.scss, app/views/search/index.html.erb
sample css class for roominess.
=> add spacing around homepage search box

app/assets/stylesheets/_hint.scss, app/assets/stylesheets/application.scss
This PR adds some hint styles in case we need them for surfacing DBs in the short term.
NOTE: The HTML example commit should be removed before merge.
=> Hint styles

app/assets/stylesheets/_search.scss
This PR makes the "found" anchor links more subtle on desktop since they aren't as useful as anchors on the large screen and are confusing users.
- https://mitlibraries.atlassian.net/browse/DI-427
=> make anchor links more subtle on desktop

app/models/normalize_eds_articles.rb, test/models/normalize_eds_articles_test.rb, test/vcr_cassettes/no_bibrecord_bibentity_articles.yml
**READY**
This is a bugfix for https://mitlibraries.atlassian.net/browse/DI-433
The code was expecting data to be available that was not. This handles
the case where the data will not be available.
In production, searching for `Al Rahmaniyah Mosque` throws an error.
This PR build will return appropriate results for the same search.
- https://mitlibraries.atlassian.net/browse/DI-433
NO
NO
=> Handles records without bibrecord bibentity data

app/models/normalize_eds_articles.rb, test/models/normalize_eds_test.rb, test/vcr_cassettes/National_Cyclopaedia_of_American_Biography.yml
**READY**
This fixes a bug in which we failed to recover from records missing expected metadata
Search for `National Cyclopaedia of American Biography` in production and in this PR build. One works!
NO
NO
=> Handles records missing expected metadata

README.md, app.json, app/models/aleph_hint.rb, app/models/hint.rb, app/models/result.rb, config/environments/test.rb, config/secrets.yml, test/fixtures/hints.yml, test/models/aleph_hint_test.rb, test/models/hint_test.rb, test/vcr_cassettes/aleph_hint.yml, test/vcr_cassettes/aleph_hint_loader_error.yml
**READY**
* loads hints from web accessible marcxml
* fingerprints are generated from title and alt title fields
After setting an appropriate value for `ALEPH_HINT_SOURCE` (see LastPass or Heroku directly) you can:
```
heroku local:run rails console
Hint.count (observe small number)
AlephHint.new.process_records
(wait)
Hint.count (observe much larger number)
```
- https://mitlibraries.atlassian.net/browse/DI-445
NO
YES, but not a gem dependency. In this case, `ALEPH_HINT_SOURCE` has been added to ENV
=> Loads Hints from web accessible marcxml

lib/tasks/reloadhints.rake
**READY**
Fixes typo
Code reading should suffice
NO
NO
=> Double quotes required for interpolation

config/features.rb
**READY**
Local full record should be false by default, and toggle-able to true.
This makes that the case.
The PR build for this should have full record disabled by default. You can toggle it back on via ENV or url switch.
NO
NO
=> Sets local full record to false

test/integration/record_test.rb, test/integration/search_test.rb, test/vcr_cassettes/record_course_reserve.yml
**READY**
- adds test to ensure course reserve material is viewable
- adds test to ensure local or remote full record links are used
Test coverage increases (no functional changes included in this PR)
- https://mitlibraries.atlassian.net/browse/DI-521
NO
NO
=> Adds missing tests

app/assets/javascripts/aleph.js, app/views/aleph/item_status.html.erb, app/views/layouts/_head.html.erb
**READY**
Adds toggles to long location lists in bento view
- https://mitlibraries.atlassian.net/browse/DI-526
NO
NO
=> Adds toggles to long location lists

app/assets/javascripts/aleph.js, app/assets/stylesheets/_aleph.scss, app/assets/stylesheets/_results.scss, app/assets/stylesheets/_variables.scss, app/assets/stylesheets/libraries-global.scss, app/views/aleph/item_status.html.erb
**READY**
Fixes the background color and class mismatch for show more toggle.
=> fix show more bugs

app/assets/stylesheets/_hint.scss
**HOLD**
This PR creates an alternate styling for the hints UI in hopes of making it more noticeable. This PR is on HOLD pending testing of the new style. 
- https://mitlibraries.atlassian.net/browse/DI-475
=> alternate more obvious hint style

app/views/record/_basic_info.html.erb, app/views/record/_sidebar.html.erb
**READY**
A few small fixes from the last PR that didn't make the cut.
=> remove extra colon, fixup sidebar

app/models/aleph_item.rb, app/models/button_maker.rb, app/views/aleph/_list_local_locations.html.erb, test/integration/aleph_test.rb, test/integration/record_test.rb, test/models/aleph_item_test.rb
**READY**
Makes a few small changes to address issues coming out of user testing on the full record.
View full record, look at availability section.
`/record/cat00916a/mit.002561380`
- https://mitlibraries.atlassian.net/browse/DI-585
=> User testing fixes

app/assets/stylesheets/_full-record.scss, app/views/record/_sidebar.html.erb
**READY**
Adds Ask Us to the sidebar of the full record.
View full record and look at the sidebar. 
- https://mitlibraries.atlassian.net/browse/DI-598
=> Add ask us to FR sidebar

app/helpers/record_helper.rb, app/views/record/_sidebar.html.erb, test/integration/record_test.rb
**READY**
De-jankifies sidebar links.
Observe sidebar of your favorite record in the PR build.
- https://mitlibraries.atlassian.net/browse/DI-599
NO
NO
=> Fix sidebar links

app/views/record/_basic_info.html.erb
**READY**
Tests for presence of metadata before displaying content that expects it (labels, parentheses around it, etc.)
- https://mitlibraries.atlassian.net/browse/DI-606 (ticket for actual work)
- https://mitlibraries.atlassian.net/browse/DI-593 (in-depth discussion with UX about issues)
NO
NO
=> Wrap metadata display in present? conditionals

app/helpers/aleph_helper.rb, test/integration/aleph_test.rb, test/vcr_cassettes/record_status_lsa.yml
**READY/IN DEVELOPMENT/HOLD**
* includes an LSA page url for the location icon in availability
https://mit-bento-staging-pr-301.herokuapp.com/record/cat00916a/mit.000171802
vs
https://mit-bento-staging.herokuapp.com/record/cat00916a/mit.000171802
- https://mitlibraries.atlassian.net/browse/DI-629
NO
NO
=> Include link to LSA page for LSA items

app/models/button_maker.rb
**READY**
changes a single word
Must you really, though?
- https://mitlibraries.atlassian.net/browse/DI-644
NO
NO
=> Wording tweak

app/helpers/aleph_helper.rb, test/integration/aleph_test.rb
**READY/**
Updates map links
Look at the PR build; observe where you end up when you click the links - it should be a page with a map, with the pin for your chosen location highlighted
- https://mitlibraries.atlassian.net/browse/DI-642
NO
NO
=> Update map links to preferred format

app/assets/javascripts/aleph.js, app/assets/stylesheets/_aleph.scss, app/assets/stylesheets/_full-record.scss, app/assets/stylesheets/_search.scss, app/assets/stylesheets/libraries-global.scss, app/views/aleph/full_item_status.html.erb, app/views/aleph/item_status.html.erb
**READY**
The PR adjusts the show more on the full record page to show more items (~10).
- https://mitlibraries.atlassian.net/browse/DI-596
YES | NO
YES | NO
=> change show more on full record page to show more items by default

app/models/normalize_eds_common.rb, test/models/normalize_eds_test.rb, test/vcr_cassettes/popcorn_books_rollbar_180.yml
**READY**
Bug fix for handling of multiple pub types in bento view
search for `popcorn` on staging and this PR. On staging you'll get an error in the books bucket. In this PR you should get results. Note that one of the results has no Publication Type... but it isn't broken now at least. 🙈 
- https://mitlibraries.atlassian.net/browse/DI-662
NO
NO
=> Bug fix in bento view pub types

app/views/record/_extended_info.html.erb
**READY**
The information in this field is sometimes summary holdings and
sometimes table of contents and sometimes other stuff. Yay.
Search for a thing. See the full record and note the wonderful variability on what shows up in this field.
- https://mitlibraries.atlassian.net/browse/DI-648
NO
NO
=> Adds content notes to extended record information

app/controllers/feature_controller.rb, app/helpers/record_helper.rb, test/features/toggle_fullrecord_test.rb
**READY**
Changes link text and flash message.
In the PR build, toggle between enabled and disabled state of in full record view.
- https://mitlibraries.atlassian.net/browse/DI-661
NO
NO
=> Full record toggle wording update

app/helpers/aleph_helper.rb, app/views/aleph/_list_local_locations.html.erb, test/helpers/aleph_helper_test.rb
**READY**
Marginally improves a poor situation with a better link.
Compare
https://mit-bento-staging.herokuapp.com/record/cat00916a/mit.000297056
with /record/cat00916a/mit.000297056 in the PR build.
The link should now go to the full holdings page.
- https://mitlibraries.atlassian.net/browse/DI-665
NO
NO
=> Aleph Holdings Link goes to Aleph Holdings Page

app/models/button_maker.rb, test/models/button_maker_test.rb
**READY**
Decouples ILL and recall/hold logic and hopefully doesn't create more bugs than it fixes.
It probably creates more bugs than it fixes. (Melissa checked the PR build and signed off that this _ seems_ to not introduce bugs)
See ticket for test records.
- https://mitlibraries.atlassian.net/browse/DI-660
NO
NO
=> should you get it here bug fix

app/models/aleph_item.rb, app/models/button_contact.rb, app/models/button_hold_recall.rb, app/models/button_ill.rb, app/models/button_maker.rb, app/models/button_scan.rb, test/models/button_contact_test.rb, test/models/button_hold_recall_test.rb, test/models/button_ill_test.rb, test/models/button_maker_test.rb, test/models/button_scan_test.rb
**READY**
Moves common button methods to a module and unique elements to independent classes in the hopes of making a more easily reasoned implementation of our complex business rules.
Hold and Recall buttons remain so tightly coupled that they share a class even in this refactor.
I was careful to keep all existing tests and just changed method calls or stubs as appropriate to match the new classes. However, see the note below about how some of the tests don't seem to work as expected after the refactor and need additional work.
NOT DONE YET: 
There should be no user facing changes. This is all read the code stuff. Before merging I will have stakeholders test the PR build fully.
- https://mitlibraries.atlassian.net/browse/DI-666
NO
NO
=> Refactor buttons

app/assets/stylesheets/_aleph.scss, app/models/button_scan.rb, app/views/aleph/_list_local_locations.html.erb, app/views/aleph/full_item_status.html.erb, app/views/record/_availability.html.erb
**READY**
Addresses small fixes from testing
View full record in the attached sandbox.
- [DI-676](https://mitlibraries.atlassian.net/browse/DI-676)
- [DI-677](https://mitlibraries.atlassian.net/browse/DI-677)
- [DI-678](https://mitlibraries.atlassian.net/browse/DI-678) 
NO
NO
=> Small changes coming out of testing

app/views/layouts/_js_exception_handler.erb
**READY**
Per the title. See inline comments for specifics.
¯\_(ツ)_/¯
Hopefully this will result in our top 3 irrelevant errors going away.  You might be able to visit the PR build vs production from Chrome on iOS and Firefox and see if error reporting is different.
- https://mitlibraries.atlassian.net/browse/DI-
NO
NO
=> Suppress noisy yet irrelevant JS

app.json
Removing workers from PR builds
NO
NO
=> Disabling worker dyno in pr builds to match prod /stage

app/controllers/record_controller.rb, test/controllers/record_controller_test.rb, test/vcr_cassettes/record_simultaneous_user_limit_reached.yml, test/vcr_cassettes/record_unknown_error_handler.yml
**READY**
We were handling all EDS record failures the same, but we have seen two distinct cases in production so this handles those more clearly. We will also continue to handle the generic case to ensure we are seeing in our logs when all of these types happen and respond as appropriate.
- https://mitlibraries.atlassian.net/browse/DI-721
NO
NO
=> Handle different failed EDS record responses

app/models/normalize_eds.rb, test/models/normalize_eds_test.rb
**READY**
This primarily logs more detail than we currently have so we can better understand what is going wrong when we see these errors.
- https://mitlibraries.atlassian.net/browse/DI-716
NO
NO
=> Handle and log invalid results

README.md
**READY**
Adds documentation on how to load hints on a heroku app.
NO
NO
=> Add docs on how to update hints on heroku

app/models/search_eds.rb
**READY**
This uses a persistent connection within a single rails request.
Since the EDS API calls require 4 calls to make a single search this should reduce overheard for doing that.
https://github.com/httprb/http/wiki/Persistent-Connections-%28keep-alive%29
🤷‍♀️ 
NO
NO
=> Changes custom EDS API calls to use persistent connections

app/models/search_eds.rb
**READY**
Sets an explicit timeout for our various EDS calls.
Previously we only had timeouts explicitly set for the main search request. Our production error reports clearly show that the other calls also hang regularly and should have had this setting applied.
NO
NO
=> Apply http timeouts to all eds calls

Gemfile.lock, app/models/search_eds.rb, test/models/search_eds_test.rb
**READY**
- updates http gem dependency
- the way the gem handles timeouts has changed so some minor adjustments were necessary to reflect these changes
NO
YES
=> update http gem dependency

app/models/button_ill.rb, app/views/search/bento.html.erb, test/models/button_ill_test.rb
**READY**
We're changing versions of the WorldCat UI and this should dump users into the new one.
- https://mitlibraries.atlassian.net/browse/DI-796
NO
NO
=> Update various links to worldcat

app/models/custom_hint.rb, test/models/custom_hint_test.rb, test/vcr_cassettes/custom_hint.yml
**READY**
Removes all dropbox requirements for hint loading
NO
NO
=> Removes all dropbox requirements for hints

app/models/search_eds.rb
**READY**
I've gone through many recent issues that triggered this in our logs and this seems to successfully resolve it.
- https://mitlibraries.atlassian.net/browse/DI-799 (see linked Sentry logs for variants of searches that caused this issue)
NO
NO
=> replaces colons sent to EDS

app/models/aleph_item.rb, app/models/button_hold_recall.rb, app/views/aleph/_list_local_locations.html.erb
**READY**
Adds worldcatinator links if the library is 
- https://mitlibraries.atlassian.net/browse/DI-806
NO
NO
=> adds worlcatinator links

README.md, app.json, app/assets/stylesheets/_results.scss, app/controllers/search_controller.rb, app/helpers/search_helper.rb, app/models/normalize_timdex.rb, app/models/result.rb, app/models/search_timdex.rb, app/views/layouts/_site_footer.html.erb, app/views/search/_other_resources.html.erb, app/views/search/_result.html.erb, app/views/search/bento.html.erb, config/environments/test.rb, test/integration/search_test.rb, test/models/normalize_timdex_test.rb, test/models/result_test.rb, test/models/search_timdex_test.rb, test/vcr_cassettes/aspace_timdex.yml, test/vcr_cassettes/popcorn_timdex.yml
This PR will probably end up getting deleted, or at least heavily rebased. Mostly, I'm impatient to poke around a bit and get back into this codebase.
- https://mitlibraries.atlassian.net/browse/DI-810 (graphQL syntax)
- https://mitlibraries.atlassian.net/browse/DI-811 (model/tests)
- https://mitlibraries.atlassian.net/browse/DI-813 (views/controller)
- https://mitlibraries.atlassian.net/browse/DI-822 (fields being used)
- https://mitlibraries.atlassian.net/browse/DI-823 (app.json structure)
NO
NO
=> Adds ArchivesSpace search panel via the TIMDEX! GraphQL endpoint

.github/workflows/ci.yml
**READY**
Upstream Action updated to allow us to stop handling bundler on our own
The CI should still pass
NO
NO
=> upstream action updated to handle bundler for us

app/controllers/record_controller.rb, test/controllers/record_controller_test.rb, test/vcr_cassettes/record_not_found.yml
This better handles a case that changed with the update of the EDS gem and treats a record not found as a 404 instead of an exception.
(coming soon)
- https://mitlibraries.atlassian.net/browse/ENGX-44
NO
NO
=> Handles record not found errors from EDS gem

README.md, app/controllers/record_controller.rb
**READY**
Updates full record views to use configurable EDS API endpoint
set a specific EDS host (ask on slack) instead of the default and if the load balanced version is broken it should now work
NO
NO
=> Updates full record views to use configurable EDS API endpoint

README.md, app/concerns/sfx_handler.rb, app/models/aleph_item.rb, app/models/button_hold_recall.rb, app/models/button_maker.rb, app/models/button_request_digital.rb, config/environments/test.rb, config/features.rb, test/models/button_scan_test.rb
Enables `Request digital copy` button for appropriate Aleph records.
We're using the same logic as the button in Aleph.
https://docs.google.com/document/d/15Z6gAu4E0784QwYEXH-6kcO8TqHVTfoe_i-dzusGPt8/edit#heading=h.aldraxogy28l
UX will be confirming this so likely just focus on the code and not the "it works as expected" part.
That said, you can use the PR build to test various types of records to ensure the Request Digital button shows up and works as expected... ask in Slack for sample records if you want to see the records I had in developing this. 
- https://mitlibraries.atlassian.net/browse/DI-829
- https://mitlibraries.atlassian.net/browse/DI-830
NO
NO
=> Request digital copy button

README.md
Corrects wrong default setting in readme. You had one job documentation!
NO
NO
=> Update readme to reflect correct default setting

app/models/aleph_item.rb, app/models/button_request_digital.rb, app/models/concerns/processing_labeler.rb
- Status 24 items (high use, usually on resevre) not eligible for Request Item, but need to be eligible for Request Digital Copy
https://mitlibraries.atlassian.net/browse/DI-932
- Also removes the note to ask at desk for reserve items
NO
NO
=> All request digital for available reserve items

README.md, app/controllers/search_controller.rb, app/helpers/search_helper.rb, app/models/normalize_primo.rb, app/models/normalize_primo_articles.rb, app/models/normalize_primo_books.rb, app/models/normalize_primo_common.rb, app/models/result.rb, app/views/search/_result.html.erb, config/environments/test.rb, test/integration/search_test.rb, test/models/normalize_primo_articles_test.rb, test/models/normalize_primo_books_test.rb, test/models/normalize_primo_test.rb, test/vcr_cassettes/missing_fields_primo.yml, test/vcr_cassettes/missing_fields_primo_articles.yml, test/vcr_cassettes/missing_fields_primo_books.yml, test/vcr_cassettes/no_results_primo.yml, test/vcr_cassettes/physical_book_primo.yml, test/vcr_cassettes/popcorn_primo.yml
The app can currently search Primo and return raw results, but it cannot
normalize those results and map them into our Result model.
* https://mitlibraries.atlassian.net/browse/IMP-1953
This adds the relevant normalization models for Primo to map Primo search
results (both Alma and CDI) into our Result model to render in the result
partial. Primo searches can now be seen in the search_boxed view using
the 'alma' and 'cdi' targets.
* Ex Libris has minimal useful documentation on the Primo Search API, so
this code will likely need to be refined over time.
* In an effort to keep things as simple as possible, this changeset
largely mirrors the logic for EDS normalization and minimizes changes
to the Result model and corresponding views. Because of this, some of the
code is a little more …
=> IMP-1953 Add normalization models for Primo searches

README.md, app/models/normalize_primo.rb, app/models/normalize_primo_articles.rb, app/models/normalize_primo_books.rb, app/models/normalize_primo_common.rb, app/views/search/_result.html.erb, app/views/search/_view_all_link.html.erb, config/environments/test.rb, config/features.rb, db/schema.rb, test/models/normalize_primo_articles_test.rb, test/models/normalize_primo_books_test.rb, test/models/normalize_primo_test.rb, test/vcr_cassettes/local_journal_primo.yml, test/vcr_cassettes/missing_fields_primo_chapter.yml, test/vcr_cassettes/primo_chapter.yml
These changes were requested as part of a UX review of the initial work
on IMP-1953. The following change requests are not included, as they
require Alma APIs:
* Location/holding data for individual volumes of an item.
* Displaying multiple copies of an item in the same location.
* Summary holdings information for serials.
These features will be added as success criteria to IMP-1773.
* https://mitlibraries.atlassian.net/browse/IMP-1953
* https://mitlibraries.atlassian.net/browse/IMP-1773
* Adds publication info for reference entries and book chapters, and
adds normalization for book chapters.
* Fixes 'View more' link to redirect to the Primo UI.
* Fixes bug in result view partial that prevented author links from
rendering for CDI results.
* Updates author and subject links to use the …
=> Implement stakeholder feedback for IMP-1953

app/helpers/search_helper.rb, app/views/search/bento.html.erb
The new Bento UI mockups include some language tweaks.
* https://mitlibraries.atlassian.net/browse/IMP-2073
This makes the changes specified in the mockups.
None.
NO
NO
=> IMP-2073 Update UI text according to latest mockups

app/views/search/bento.html.erb
An additional tweak to the UI text was identified in UX review.
* https://mitlibraries.atlassian.net/browse/IMP-2073
Removes ': MIT catalog' from the totals summary.
None.
NO
NO
=> Small update to UI copy

app/views/search/_other_resources.html.erb
The copy in this partial references services that will no longer exist.
* https://mitlibraries.atlassian.net/browse/IMP-2076
This updates the copy as specified by UX.
None.
NO
NO
=> IMP-2076 Update copy in _other_resources partial

app/views/search/_view_all_link.html.erb
https://mitlibraries.atlassian.net/browse/PW-81
It's unclear why this only became a problem recently, so this may not address the underlying problem, but it does seem to fix the immediate concern.
NO
NO
=> Ensure total is an integer before comparison

app/views/search/bento.html.erb, public/google1ac9eb720e88154a.html
* Adds google developer console ownership file
* Adds noindex, nofollow headers on all results pages
https://mitlibraries.atlassian.net/browse/PW-146
NO
NO
=> Adds search engine directives to results pages
